import { ClinicalQuestion } from '../types';

export const AGNI_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'AY-AGNI-APPETITE-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'agni',
    section: 'ayush_agni',
    category: 'appetite',
    questionText: {
      en: 'How would you describe your appetite and hunger pattern usually?',
      ta: 'உங்கள் பசி மற்றும் உணவருந்தும் உணர்வை எப்படி விவரிப்பீர்கள்?',
      hi: 'आप अपनी भूख और खाने की इच्छा को कैसा महसूस करते हैं?',
    },
    answerType: 'single_choice',
    targetField: 'appetite_pattern',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
    choices: [
      { value: 'normal_sama', label: { en: 'Normal healthy appetite at regular times', ta: 'சீரான இயல்பான பசி', hi: 'सामान्य और सही समय पर भूख' } },
      { value: 'poor_manda', label: { en: 'Poor / sluggish appetite (don’t feel hungry)', ta: 'பசியின்மை / குறைந்த பசி', hi: 'कमजोरी या भूख न लगना' } },
      { value: 'sharp_tikshna', label: { en: 'Excessive / intense hunger (cannot tolerate delay)', ta: 'அதிகமான பசி (தாமதித்தால் தாங்க முடியாது)', hi: 'बहुत ज्यादा भूख (देर सहन न होना)' } },
      { value: 'variable_vishama', label: { en: 'Irregular / variable (sometimes very hungry, sometimes none)', ta: 'மாறி மாறி வரும் சீரற்ற பசி', hi: 'अनियमित (कभी तेज भूख, कभी बिल्कुल नहीं)' } },
    ],
  },
  {
    id: 'AY-AGNI-BLOATING-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'agni',
    section: 'ayush_agni',
    category: 'digestion',
    questionText: {
      en: 'Do you feel heavy, bloated, or gas-filled immediately after eating a normal meal?',
      ta: 'சாப்பிட்டவுடன் வயிறு கனமாகி காற்று அடைத்தது போல உப்பசமாக இருக்குமா?',
      hi: 'क्या खाना खाने के तुरंत बाद पेट भारी, फूला हुआ या गैस से भरा महसूस होता है?',
    },
    answerType: 'yes_no',
    targetField: 'postprandial_fullness_gas',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
  },
  {
    id: 'AY-AGNI-BURNING-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'agni',
    section: 'ayush_agni',
    category: 'digestion',
    questionText: {
      en: 'Do you experience sour belching, acid reflux, or burning in your chest/stomach?',
      ta: 'உங்களுக்கு புளிப்பு ஏப்பம், நெஞ்செரிச்சல் அல்லது வயிற்றில் எரிச்சல் ஏற்படுகிறதா?',
      hi: 'क्या आपको खट्टी डकारें, सीने में जलन या पेट में जलन होती है?',
    },
    answerType: 'yes_no',
    targetField: 'acid_reflux_belching',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
  },
];
