import { ClinicalQuestion } from '../types';

export const AHARA_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'AY-AHARA-MEALTIME-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ahara',
    section: 'ayush_ahara',
    category: 'meal_habit',
    questionText: {
      en: 'Do you usually eat your meals at regular fixed times every day?',
      ta: 'நீங்கள் தினமும் குறிப்பிட்ட சரியான நேரத்தில் உணவு சாப்பிடும் பழக்கம் உடையவரா?',
      hi: 'क्या आप आमतौर पर रोज तय समय पर खाना खाते हैं?',
    },
    answerType: 'single_choice',
    targetField: 'meal_regularity',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
    choices: [
      { value: 'regular', label: { en: 'Regular fixed times', ta: 'சரியான நேரத்தில்', hi: 'नियमित समय पर' } },
      { value: 'irregular', label: { en: 'Irregular timings / frequently delayed', ta: 'நேரம் தவறி சாப்பிடுதல்', hi: 'अनियमित समय / अक्सर देरी' } },
    ],
  },
  {
    id: 'AY-AHARA-SKIP-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ahara',
    section: 'ayush_ahara',
    category: 'meal_habit',
    questionText: {
      en: 'Do you frequently skip breakfast or any main meal?',
      ta: 'காலை உணவையோ அல்லது முக்கிய உணவையோ அடிக்கடி தவிர்க்கும் பழக்கம் உள்ளதா?',
      hi: 'क्या आप अक्सर नाश्ता या कोई मुख्य खाना छोड़ देते हैं?',
    },
    answerType: 'yes_no',
    targetField: 'skips_breakfast_meals',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
  },
  {
    id: 'AY-AHARA-TASTE-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ahara',
    section: 'ayush_ahara',
    category: 'diet',
    questionText: {
      en: 'What kind of foods do you eat or crave most frequently?',
      ta: 'நீங்கள் எந்த வகையான உணவுகளை அதிகம் விரும்பி சாப்பிடுகிறீர்கள்?',
      hi: 'आप किस तरह का खाना ज्यादा पसंद करते हैं?',
    },
    answerType: 'multi_choice',
    targetField: 'dietary_taste_preference',
    priority: 75,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
    choices: [
      { value: 'spicy', label: { en: 'Very spicy food', ta: 'காரமான உணவு', hi: 'बहुत तीखा/मसालेदार खाना' } },
      { value: 'oily_fried', label: { en: 'Oily and fried snacks', ta: 'எண்ணெய் பலகாரங்கள்', hi: 'तला-भुना खाना' } },
      { value: 'salty', label: { en: 'High salt / pickles', ta: 'அதிக உப்பு / ஊறுகாய்', hi: 'ज्यादा नमक / अचार' } },
      { value: 'sweets', label: { en: 'Sweets and desserts', ta: 'இனிப்புகள்', hi: 'मीठे व्यंजन' } },
      { value: 'sour', label: { en: 'Sour foods / curd', ta: 'புளிப்பான உணவு / தயிர்', hi: 'खट्टा खाना / दही' } },
    ],
  },
  {
    id: 'AY-AHARA-WATER-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ahara',
    section: 'ayush_ahara',
    category: 'diet',
    questionText: {
      en: 'Approximately how much water do you drink per day?',
      ta: 'ஒரு நாளைக்கு தோராயமாக எவ்வளவு தண்ணீர் குடிக்கிறீர்கள்?',
      hi: 'आप एक दिन में लगभग कितना पानी पीते हैं?',
    },
    answerType: 'single_choice',
    targetField: 'daily_water_intake',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
    choices: [
      { value: 'under_1l', label: { en: 'Less than 1 liter per day', ta: '1 லிட்டருக்கும் குறைவு', hi: '1 लीटर से कम' } },
      { value: '1_to_2l', label: { en: '1 to 2 liters per day', ta: '1 முதல் 2 லிட்டர்', hi: '1 से 2 लीटर' } },
      { value: 'over_2l', label: { en: 'More than 2 to 3 liters', ta: '2 லிட்டருக்கும் மேல்', hi: '2 लीटर से अधिक' } },
    ],
  },
  {
    id: 'AY-AHARA-TEA-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ahara',
    section: 'ayush_ahara',
    category: 'diet',
    questionText: {
      en: 'How many cups of tea or coffee do you drink daily?',
      ta: 'தினமும் எத்தனை கப் டீ அல்லது காபி குடிக்கிறீர்கள்?',
      hi: 'आप रोज कितने कप चाय या कॉफी पीते हैं?',
    },
    answerType: 'numeric',
    targetField: 'caffeine_tea_cups_daily',
    priority: 75,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
  },
];
