import { ClinicalQuestion } from '../types';

export const ASHTAVIDHA_QUESTIONS: ClinicalQuestion[] = [
  // 1. Nadi (Pulse Diagnosis - Clinician Exam)
  {
    id: 'AY-ASHTA-NADI-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ashtavidha',
    section: 'ashtavidha_pariksha',
    category: 'nadi',
    ayushDomain: 'nadi',
    questionText: {
      en: 'Radial pulse examination (Nadi Pariksha) for rate, rhythm, movement character, and dosha dominance.',
      ta: 'நாடி பரிசோதனை (நாடி நடை, வேகம் மற்றும் தோஷ நிலை).',
      hi: 'नाड़ी परीक्षा (गति, लय और दोषों का नाड़ी प्रभाव)।',
    },
    answerType: 'single_choice',
    targetField: 'nadi_examination_findings',
    priority: 90,
    required: false,
    voiceEnabled: false,
    touchEnabled: true,
    sourceType: 'clinician_assessment',
    choices: [
      { value: 'vata_gati', label: { en: 'Vata Nadi (Serpentine / Quick & irregular like a snake)', ta: 'வாத நாடி (பாம்பு நடை / சீரற்ற வேகம்)', hi: 'वात नाड़ी (सर्प गति / तीव्र और अनियंत्रित)' } },
      { value: 'pitta_gati', label: { en: 'Pitta Nadi (Bounding / Frog-like jump)', ta: 'பித்த நாடி (தவளை நடை / துள்ளல் வேகம்)', hi: 'पित्त नाड़ी (मंडूक गति / उछलती हुई)' } },
      { value: 'kapha_gati', label: { en: 'Kapha Nadi (Slow / Swan-like steady movement)', ta: 'கப நாடி (அன்னநடை / நிதானமான வேகம்)', hi: 'कफ नाड़ी (हंस गति / धीमी और स्थिर)' } },
      { value: 'sannipata_mixed', label: { en: 'Sannipata / Dual Dosha (Mixed pulse characteristics)', ta: 'தொந்த நாடி / கலப்பு நாடி', hi: 'सन्निपात / मिश्रित नाड़ी' } },
    ],
  },
  // 2. Jihva (Tongue Examination - Clinician visual observation)
  {
    id: 'AY-ASHTA-JIHVA-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ashtavidha',
    section: 'ashtavidha_pariksha',
    category: 'jihva',
    ayushDomain: 'jihva',
    questionText: {
      en: 'Visual inspection of tongue for coating (Sama/Nirama), moisture, color, and tremors.',
      ta: 'நாக்கின் நிறம், ஈரம், படிவு (சாமா / நிராமா) பற்றிய பரிசோதனை.',
      hi: 'जीभ का लेप (साम/निराम), नमी और रंग का निरीक्षण।',
    },
    answerType: 'single_choice',
    targetField: 'jihva_tongue_coating',
    priority: 85,
    required: false,
    voiceEnabled: false,
    touchEnabled: true,
    sourceType: 'clinician_assessment',
    choices: [
      { value: 'clear_nirama', label: { en: 'Clear & pink (Nirama / No toxic coating)', ta: 'தெளிவான இளஞ்சிவப்பு (நிராமா)', hi: 'साफ और गुलाबी (निराम)' } },
      { value: 'white_coated_sama', label: { en: 'Thick white coating (Sama / Ama present)', ta: 'தடித்த வெள்ளை படிவு (சாமா)', hi: 'सफेद मोटी परत (साम)' } },
      { value: 'dry_cracked', label: { en: 'Dry, dark, or cracked tongue', ta: 'வறண்ட / விரிசல் விழுந்த நாக்கு', hi: 'सूखी या दरारयुक्त जीभ' } },
      { value: 'red_yellowish', label: { en: 'Red or yellowish coated tongue', ta: 'சிவப்பு / மஞ்சள் படிந்த நாக்கு', hi: 'लाल या पीली परत वाली जीभ' } },
    ],
  },
  // 3. Mala (Stool Pattern - Patient Reportable)
  {
    id: 'AY-ASHTA-MALA-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ashtavidha',
    section: 'ashtavidha_pariksha',
    category: 'mala',
    ayushDomain: 'mala',
    questionText: {
      en: 'How would you describe your stool consistency and evacuation routine?',
      ta: 'உங்கள் மலம் கழிக்கும் முறை மற்றும் மலத்தின் தன்மை எவ்வாறு உள்ளது?',
      hi: 'मल की स्थिति और शौच की दिनचर्या कैसी है?',
    },
    answerType: 'single_choice',
    targetField: 'mala_bowel_characteristics',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
    choices: [
      { value: 'formed_normal', label: { en: 'Formed, smooth, regular once or twice daily', ta: 'சீரான இயல்பான மலம்', hi: 'सामान्य और नियमित शौच' } },
      { value: 'hard_constipated', label: { en: 'Hard, dry, dark pellets with straining', ta: 'கடினமான, வறண்ட மலம் / மலச்சிக்கல்', hi: 'कड़ा, सूखा मल या कब्ज' } },
      { value: 'loose_frequent', label: { en: 'Loose, watery, or urgent liquid bowel movements', ta: 'இளகிய / நீர் போன்ற மலம்', hi: 'पतला या बार-बार शौच' } },
      { value: 'sticky_ama', label: { en: 'Sticky, foul-smelling, heavy stool that sticks to toilet pan', ta: 'பிசுபிசுப்பான, துர்நாற்றமுள்ள மலம் (ஆமம்)', hi: 'चिपचिपा, दुर्गंधयुक्त मल' } },
    ],
  },
  // 4. Mutra (Urine Pattern - Patient Reportable)
  {
    id: 'AY-ASHTA-MUTRA-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ashtavidha',
    section: 'ashtavidha_pariksha',
    category: 'mutra',
    ayushDomain: 'mutra',
    questionText: {
      en: 'How is your urine color, daily frequency, and do you experience burning or urgency?',
      ta: 'சிறுநீரின் நிறம், அளவு மற்றும் எரிச்சல் ஏதேனும் உள்ளதா?',
      hi: 'पेशाब का रंग, मात्रा और क्या जलन या बार-बार जाने की इच्छा होती है?',
    },
    answerType: 'single_choice',
    targetField: 'mutra_urine_characteristics',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
    choices: [
      { value: 'normal_clear', label: { en: 'Clear or light yellow, normal frequency without pain', ta: 'தெளிவான இயல்பான சிறுநீர்', hi: 'साफ, सामान्य पेशाब' } },
      { value: 'scanty_dark_yellow', label: { en: 'Dark yellow, concentrated, or reduced output', ta: 'அடர்ந்த மஞ்சள் / குறைந்த அளவு', hi: 'गहरा पीला या कम पेशाब' } },
      { value: 'burning_dysuria', label: { en: 'Burning sensation or urgency during urination', ta: 'சிறுநீர் கழிக்கும் போது எரிச்சல்', hi: 'पेशाब करते समय जलन' } },
      { value: 'profuse_clear', label: { en: 'Excessive, profuse clear urination (frequent day & night)', ta: 'அதிகளவிலான அடிக்கடி தெளிவான சிறுநீர்', hi: 'अत्यधिक और बार-बार पेशाब' } },
    ],
  },
  // 5. Shabda (Voice & Acoustic examination - Clinician assessment)
  {
    id: 'AY-ASHTA-SHABDA-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ashtavidha',
    section: 'ashtavidha_pariksha',
    category: 'shabda',
    ayushDomain: 'shabda',
    questionText: {
      en: 'Acoustic evaluation of voice pitch, clarity, hoarseness, and bowel/respiratory sounds.',
      ta: 'குரலின் தொனி, கரகரப்பு மற்றும் சுவாச ஒலிகள் பரிசோதனை.',
      hi: 'आवाज की स्पष्टता, भारीपन और सांस/आंतों की आवाज का परीक्षण।',
    },
    answerType: 'single_choice',
    targetField: 'shabda_voice_character',
    priority: 70,
    required: false,
    voiceEnabled: false,
    touchEnabled: true,
    sourceType: 'clinician_assessment',
    choices: [
      { value: 'normal_resonant', label: { en: 'Clear, resonant, steady voice', ta: 'தெளிவான கம்பீரமான குரல்', hi: 'स्पष्ट और गंभीर आवाज' } },
      { value: 'hoarse_dry', label: { en: 'Hoarse, weak, or dry voice', ta: 'கரகரப்பான / பலவீனமான குரல்', hi: 'बैठी हुई या सूखी आवाज' } },
      { value: 'deep_heavy', label: { en: 'Deep, slow, or heavy voice sound', ta: 'கம்பீரமான கனமான குரல்', hi: 'गहरी और भारी आवाज' } },
    ],
  },
  // 6. Drik (Eye & Vision Examination - Clinician Visual Assessment)
  {
    id: 'AY-ASHTA-DRIK-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ashtavidha',
    section: 'ashtavidha_pariksha',
    category: 'drik',
    ayushDomain: 'drik',
    questionText: {
      en: 'Visual examination of conjunctiva, sclera, dryness, redness, or icterus in the eyes.',
      ta: 'கண்களின் நிறம், சிவப்பு, மஞ்சள் காமாலை அறிகுறி பரிசோதனை.',
      hi: 'नेत्रों का निरीक्षण (लाली, पीलापन, सूखापन या चमक)।',
    },
    answerType: 'single_choice',
    targetField: 'drik_eye_examination',
    priority: 75,
    required: false,
    voiceEnabled: false,
    touchEnabled: true,
    sourceType: 'clinician_assessment',
    choices: [
      { value: 'normal_lustrous', label: { en: 'Normal clear eyes with natural luster', ta: 'தெளிவான இயல்பான கண்கள்', hi: 'सामान्य और चमकदार आंखें' } },
      { value: 'dry_sunken', label: { en: 'Dry, dull, or sunken eyes', ta: 'வறண்ட / குழிவிழுந்த கண்கள்', hi: 'सूखी या अंदर धंसी आंखें' } },
      { value: 'red_burning', label: { en: 'Reddish, inflamed, or bloodshot eyes', ta: 'சிவந்த / அழற்சியடைந்த கண்கள்', hi: 'लाल या जलनयुक्त आंखें' } },
      { value: 'yellow_icteric', label: { en: 'Yellow sclera (icteric tint)', ta: 'மஞ்சள் நிற கண்கள்', hi: 'पीली आंखें' } },
    ],
  },
  // 7. Akriti (General Facies & Body Frame - Clinician Assessment)
  {
    id: 'AY-ASHTA-AKRITI-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ashtavidha',
    section: 'ashtavidha_pariksha',
    category: 'akriti',
    ayushDomain: 'akriti',
    questionText: {
      en: 'Observation of overall facial expression, physical physique, gait, and posture.',
      ta: 'முகப்பொலிவு, உடல் தோற்றம் மற்றும் நடக்கும் முறை பரிசோதனை.',
      hi: 'शारीरिक ढाल, चाल और चेहरे के भावों का समग्र निरीक्षण।',
    },
    answerType: 'single_choice',
    targetField: 'akriti_facies_posture',
    priority: 70,
    required: false,
    voiceEnabled: false,
    touchEnabled: true,
    sourceType: 'clinician_assessment',
    choices: [
      { value: 'thin_emaciated', label: { en: 'Lean, light frame, quick gait (Vata-dominant Akriti)', ta: 'மெலிந்த உடல்வாகு (வாத தோற்றம்)', hi: 'दुबला-पतला शरीर' } },
      { value: 'moderate_flushed', label: { en: 'Medium build, sharp features, intense expression (Pitta Akriti)', ta: 'நடுத்தர உடற்கட்டு (பித்த தோற்றம்)', hi: 'मध्यम बनावट' } },
      { value: 'broad_sturdy', label: { en: 'Large, sturdy build, calm graceful gait (Kapha Akriti)', ta: 'அகன்ற பலமான உடற்கட்டு (கப தோற்றம்)', hi: 'चौड़ा और मजबूत शरीर' } },
    ],
  },
];
