import { ClinicalQuestion } from '../types';

export const DASHAVIDHA_QUESTIONS: ClinicalQuestion[] = [
  // 1. Prakriti
  {
    id: 'AY-DA10-PRAKRITI-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'dashavidha',
    section: 'dashavidha_pariksha',
    category: 'prakriti',
    ayushDomain: 'prakriti',
    questionText: {
      en: 'Since childhood or young age, what has been your natural baseline body constitution and climate preference?',
      ta: 'சிறுவயதிலிருந்தே உங்கள் இயற்கையான உடல் இயல்பு மற்றும் காலநிலை சகிப்புத்தன்மை எவ்வாறு உள்ளது?',
      hi: 'बचपन से आपका स्वाभाविक शारीरिक स्वभाव और मौसम सहन करने की क्षमता कैसी रही है?',
    },
    answerType: 'single_choice',
    targetField: 'baseline_prakriti_features',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
    choices: [
      { value: 'cold_sensitive_vata', label: { en: 'Prefer warmth, easily feel cold or dry', ta: 'வெப்பத்தை விரும்புவேன், சீக்கிரம் குளிர்/வறட்சி அடையும்', hi: 'गर्मी पसंद है, आसानी से ठंड या सूखापन महसूस होता है' } },
      { value: 'heat_sensitive_pitta', label: { en: 'Prefer cool environment, easily get hot or sweat', ta: 'குளிர்ச்சியை விரும்புவேன், சீக்கிரம் சூடேறும்', hi: 'ठंडक पसंद है, आसानी से गर्मी महसूस होती है' } },
      { value: 'stable_moist_kapha', label: { en: 'Prefer active environment, sturdy build, tolerate cold/heat moderately', ta: 'சீரான சகிப்புத்தன்மை, பலமான உடல்', hi: 'मजबूत बनावट, मौसम सहन करने की अच्छी क्षमता' } },
    ],
  },
  // 2. Vikriti
  {
    id: 'AY-DA10-VIKRITI-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'dashavidha',
    section: 'dashavidha_pariksha',
    category: 'vikriti',
    ayushDomain: 'vikriti',
    questionText: {
      en: 'What is the main physical change or disturbance you are feeling compared to your normal baseline state?',
      ta: 'உங்கள் இயல்பான நிலையிலிருந்து தற்போது என்ன முக்கிய மாற்றம் அல்லது அசௌகரியம் தோன்றியுள்ளது?',
      hi: 'आपकी सामान्य स्थिति की तुलना में अभी आपको क्या मुख्य बदलाव या तकलीफ महसूस हो रही है?',
    },
    answerType: 'free_text',
    targetField: 'current_vikriti_deviation',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
  },
  // 3. Sara (Tissue essence - Clinician evaluation supported by patient observations)
  {
    id: 'AY-DA10-SARA-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'dashavidha',
    section: 'dashavidha_pariksha',
    category: 'sara',
    ayushDomain: 'sara',
    questionText: {
      en: 'Assessment of tissue quality, vitality, skin luster, and bone strength.',
      ta: 'திசுக்களின் தரம், தோல் பொலிவு மற்றும் எலும்பு வலிமை ஆய்வு.',
      hi: 'धातुओं की गुणवत्ता, त्वचा की चमक और हड्डियों की मजबूती का आकलन।',
    },
    answerType: 'single_choice',
    targetField: 'sara_examination_status',
    priority: 70,
    required: false,
    voiceEnabled: false,
    touchEnabled: true,
    sourceType: 'clinician_assessment',
    choices: [
      { value: 'pravara_excellent', label: { en: 'Pravara Sara (Superior tissue essence)', ta: 'பிரவர சாரம் (சிறந்த திசு பலம்)', hi: 'प्रवर सार (उत्कृष्ट धातु बल)' } },
      { value: 'madhyama_moderate', label: { en: 'Madhyama Sara (Moderate tissue essence)', ta: 'மத்தியம சாரம் (மிதமான திசு பலம்)', hi: 'मध्यम सार (मध्यम धातु बल)' } },
      { value: 'avara_poor', label: { en: 'Avara Sara (Suboptimal tissue essence)', ta: 'அவர சாரம் (குறைந்த திசு பலம்)', hi: 'अवर सार (कमजोर धातु बल)' } },
    ],
  },
  // 4. Samhanana (Compactness / Body Symmetry - Clinician physical exam)
  {
    id: 'AY-DA10-SAMHANANA-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'dashavidha',
    section: 'dashavidha_pariksha',
    category: 'samhanana',
    ayushDomain: 'samhanana',
    questionText: {
      en: 'Clinical evaluation of body compactness, bone density, and structural symmetry.',
      ta: 'உடலின் அடர்த்தி, எலும்பு அமைப்பின் கட்டமைப்பு பரிசோதனை.',
      hi: 'शारीरिक बनावट, मजबूती और शारीरिक संतुलन का नैदानिक मूल्यांकन।',
    },
    answerType: 'single_choice',
    targetField: 'samhanana_compactness',
    priority: 65,
    required: false,
    voiceEnabled: false,
    touchEnabled: true,
    sourceType: 'clinician_assessment',
    choices: [
      { value: 'su_samhanana', label: { en: 'Susamhanana (Well-compacted / symmetrical)', ta: 'சுசம்ஹனனம் (நல்ல உடற்கட்டு)', hi: 'सुसंहनन (सुगठित शरीर)' } },
      { value: 'madhyama_samhanana', label: { en: 'Madhyama Samhanana (Moderate compactness)', ta: 'மத்தியம சம்ஹனனம் (மிதமான உடற்கட்டு)', hi: 'मध्यम संहनन (मध्यम बनावट)' } },
      { value: 'heena_samhanana', label: { en: 'Heena Samhanana (Lax / poorly compacted)', ta: 'ஹீன சம்ஹனனம் (தளர்ந்த உடற்கட்டு)', hi: 'हीन संहनन (कमजोर बनावट)' } },
    ],
  },
  // 5. Pramana (Anthropometric Measurements - Height/Weight measurement)
  {
    id: 'AY-DA10-PRAMANA-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'dashavidha',
    section: 'dashavidha_pariksha',
    category: 'pramana',
    ayushDomain: 'pramana',
    questionText: {
      en: 'What is your current body height (in cm) and weight (in kg)?',
      ta: 'உங்கள் தற்போதைய உயரம் (செ.மீ) மற்றும் எடை (கிலோ) என்ன?',
      hi: 'आपकी वर्तमान लंबाई (सेमी में) और वजन (किग्रा में) कितना है?',
    },
    answerType: 'numeric',
    targetField: 'pramana_body_measurements',
    priority: 85,
    required: false,
    voiceEnabled: false,
    touchEnabled: true,
    sourceType: 'measurement_required',
  },
  // 6. Satmya (Habituation / Adaptability)
  {
    id: 'AY-DA10-SATMYA-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'dashavidha',
    section: 'dashavidha_pariksha',
    category: 'satmya',
    ayushDomain: 'satmya',
    questionText: {
      en: 'Are there particular foods, oils, or habits that your body easily tolerates and digests well?',
      ta: 'உங்கள் உடலுக்கு எளிதில் ஒத்துக்கொள்ளும் மற்றும் செரிக்கும் உணவுகள் அல்லது பழக்கவழக்கங்கள் எவை?',
      hi: 'कौन से खाद्य पदार्थ या आदतें आपके शरीर को आसानी से माफिक (सूट) आती हैं?',
    },
    answerType: 'free_text',
    targetField: 'dietary_wholesomeness_satmya',
    priority: 75,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
  },
  // 7. Sattva (Mental Strength / Coping Ability)
  {
    id: 'AY-DA10-SATTVA-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'dashavidha',
    section: 'dashavidha_pariksha',
    category: 'sattva',
    ayushDomain: 'sattva',
    questionText: {
      en: 'How well do you usually handle sudden emotional stress, bad news, or physical pain?',
      ta: 'திடீர் மனஅழுத்தம், வலி அல்லது துன்பகரமான சூழ்நிலைகளை நீங்கள் எவ்வாறு எதிர்கொள்கிறீர்கள்?',
      hi: 'अचानक तनाव, दर्द या कठिन परिस्थितियों को आप आमतौर पर कैसे संभालते हैं?',
    },
    answerType: 'single_choice',
    targetField: 'mental_resilience_sattva',
    priority: 80,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
    choices: [
      { value: 'pravara_high', label: { en: 'Strong mental composure & endurance (Pravara)', ta: 'உறுதியான மனவலிமை (பிரவரம்)', hi: 'मजबूत मानसिक धैर्य (प्रवर)' } },
      { value: 'madhyama_moderate', label: { en: 'Moderate stress tolerance with support (Madhyama)', ta: 'மிதமான மனவலிமை (மத்தியமம்)', hi: 'मध्यम मानसिक क्षमता (मध्यम)' } },
      { value: 'avara_sensitive', label: { en: 'Easily overwhelmed by distress or pain (Avara)', ta: 'எளிதில் பதற்றமடையும் மனநிலை (அவரம்)', hi: 'जल्दी घबराने वाला स्वभाव (अवर)' } },
    ],
  },
  // 8. Ahara Shakti (Digestive & Assimilation Capacity)
  {
    id: 'AY-DA10-AHARASHAKTI-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'dashavidha',
    section: 'dashavidha_pariksha',
    category: 'ahara_shakti',
    ayushDomain: 'ahara_shakti',
    questionText: {
      en: 'How would you describe your overall capacity to eat and comfortably digest food?',
      ta: 'உணவருந்தும் அளவு மற்றும் அதை செரிக்கும் திறன் எவ்வாறு உள்ளது?',
      hi: 'खाना खाने की क्षमता और उसे पचाने की शक्ति कैसी है?',
    },
    answerType: 'single_choice',
    targetField: 'ahara_shakti_capacity',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
    choices: [
      { value: 'pravara_good', label: { en: 'Good appetite & quick digestion', ta: 'நல்ல பசி மற்றும் சிறந்த செரிமானம்', hi: 'अच्छी भूख और तेज पाचन' } },
      { value: 'madhyama_moderate', label: { en: 'Moderate appetite & average digestion', ta: 'மிதமான பசி மற்றும் செரிமானம்', hi: 'सामान्य भूख और मध्यम पाचन' } },
      { value: 'avara_poor', label: { en: 'Poor appetite & sluggish digestion', ta: 'குறைந்த பசி மற்றும் மந்தமான செரிமானம்', hi: 'कम भूख और मंद पाचन' } },
    ],
  },
  // 9. Vyayama Shakti (Physical Exercise / Energy Endurance)
  {
    id: 'AY-DA10-VYAYAMASHAKTI-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'dashavidha',
    section: 'dashavidha_pariksha',
    category: 'vyayama_shakti',
    ayushDomain: 'vyayama_shakti',
    questionText: {
      en: 'How much physical exertion or daily work can you comfortably carry out before feeling exhausted?',
      ta: 'களைப்படையாமல் உங்களால் எவ்வளவு உடலுழைப்பு அல்லது வேலையைச் செய்ய முடிகிறது?',
      hi: 'बिना थके आप कितना शारीरिक काम या व्यायाम आराम से कर सकते हैं?',
    },
    answerType: 'single_choice',
    targetField: 'exercise_endurance_capacity',
    priority: 80,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
    choices: [
      { value: 'high_endurance', label: { en: 'High capacity for physical exertion', ta: 'அதிக உடலுழைப்பு திறன்', hi: 'अत्यधिक शारीरिक क्षमता' } },
      { value: 'moderate_endurance', label: { en: 'Moderate capacity for daily tasks', ta: 'மிதமான உழைப்பு திறன்', hi: 'मध्यम कार्य क्षमता' } },
      { value: 'low_endurance', label: { en: 'Gets tired quickly with mild exertion', ta: 'சிறிய வேலையிலேயே விரைவில் களைப்பு', hi: 'थोड़ी मेहनत से ही जल्दी थकान' } },
    ],
  },
  // 10. Vaya (Chronological Life Stage Context)
  {
    id: 'AY-DA10-VAYA-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'dashavidha',
    section: 'dashavidha_pariksha',
    category: 'vaya',
    ayushDomain: 'vaya',
    questionText: {
      en: 'Age/Life stage contextual assessment derived from DOB (Childhood/Bala, Middle age/Madhyama, Elderly/Vriddha).',
      ta: 'பிறந்த தேதியின் அடிப்படையிலான வாழ்வியல் நிலை ஆய்வு (பாலியம், மத்தியமம், விருத்தம்).',
      hi: 'जन्म तिथि के आधार पर जीवन काल का नैदानिक विभाजन (बाल्यावस्था, मध्यावस्था, वृद्धावस्था)।',
    },
    answerType: 'single_choice',
    targetField: 'vaya_life_stage',
    priority: 60,
    required: false,
    voiceEnabled: false,
    touchEnabled: true,
    sourceType: 'clinician_assessment',
    choices: [
      { value: 'bala_childhood', label: { en: 'Bala (Childhood / Growth phase up to 16)', ta: 'பால பருவம் (16 வயது வரை)', hi: 'बाल्यावस्था (16 वर्ष तक)' } },
      { value: 'madhyama_middle', label: { en: 'Madhyama (Adult / Youth and maturity 16-60)', ta: 'மத்தியம பருவம் (16-60 வயது)', hi: 'मध्यावस्था (16-60 वर्ष)' } },
      { value: 'vriddha_elderly', label: { en: 'Vriddha (Geriatric / Degenerative phase 60+)', ta: 'விருத்த பருவம் (60 வயதுக்கு மேல்)', hi: 'वृद्धावस्था (60+ वर्ष)' } },
    ],
  },
];
