import { ClinicalQuestion } from '../types';

export const AYUSH_GENERAL_HISTORY_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'AY-GEN-HISTORY-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ayush_general_history',
    section: 'ayush_history',
    category: 'character',
    questionText: {
      en: 'What primary health concern or discomfort brings you for an AYUSH consultation today?',
      ta: 'இன்று ஆயுஷ் மருத்துவ ஆலோசனைக்கு வந்ததன் முதன்மை காரணம் என்ன?',
      hi: 'आज आयुष परामर्श के लिए आने का मुख्य कारण क्या है?',
    },
    answerType: 'free_text',
    targetField: 'ayush_chief_complaint',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
  },
  {
    id: 'AY-GEN-DUR-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ayush_general_history',
    section: 'ayush_history',
    category: 'duration',
    questionText: {
      en: 'How long have you been experiencing this main health issue?',
      ta: 'இந்த பிரதான பிரச்சனை எவ்வளவு நாட்களாக அல்லது மாதங்களாக இருக்கிறது?',
      hi: 'यह मुख्य स्वास्थ्य समस्या कितने समय से हो रही है?',
    },
    answerType: 'duration',
    targetField: 'duration_text',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
  },
  {
    id: 'AY-GEN-PREV-TX-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'ayush_general_history',
    section: 'ayush_history',
    category: 'past_medical_history',
    questionText: {
      en: 'Have you taken any Ayurvedic, Siddha, Homeopathic, or Allopathic medicines for this condition earlier?',
      ta: 'இதற்கு முன் ஆயுர்வேத, சித்த அல்லது ஆங்கில மருந்துகள் ஏதேனும் எடுத்துள்ளீர்களா?',
      hi: 'क्या आपने इस समस्या के लिए पहले कोई आयुर्वेदिक, सिद्धा या एलोपैथिक दवा ली है?',
    },
    answerType: 'multi_choice',
    targetField: 'previous_treatments',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
    choices: [
      { value: 'ayurveda_siddha', label: { en: 'Ayurveda / Siddha medicines', ta: 'ஆயுர்வேத / சித்த மருந்துகள்', hi: 'आयुर्वेदिक / सिद्धा दवाएं' } },
      { value: 'allopathy', label: { en: 'Allopathic (English) tablets', ta: 'ஆங்கில மாத்திரைகள்', hi: 'एलोपैथिक दवाएं' } },
      { value: 'homeopathy', label: { en: 'Homeopathy', ta: 'ஹோமியோபதி', hi: 'होम्योपैथी' } },
      { value: 'none', label: { en: 'None / First time', ta: 'எதுவும் இல்லை / முதல்முறை', hi: 'कोई नहीं / पहली बार' } },
    ],
  },
];
