import { ClinicalQuestion } from '../types';

export const VIHARA_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'AY-VIHARA-ACTIVITY-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'vihara',
    section: 'ayush_vihara',
    category: 'daily_routine',
    questionText: {
      en: 'How would you describe your daily physical activity level?',
      ta: 'உங்கள் அன்றாட உடல் உழைப்பை எப்படி விவரிப்பீர்கள்?',
      hi: 'आप अपनी दैनिक शारीरिक गतिविधि के स्तर को कैसे बताएंगे?',
    },
    answerType: 'single_choice',
    targetField: 'daily_physical_activity',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
    choices: [
      { value: 'sedentary', label: { en: 'Mostly sitting (Sedentary / computer job)', ta: 'அமர்ந்தபடியே பணியாற்றுவது (கணினி வேலை)', hi: 'ज्यादातर बैठकर काम करना (कंप्यूटर जॉब)' } },
      { value: 'moderate', label: { en: 'Moderate walking or light standing', ta: 'மிதமான நடைபயிற்சி / நடமாட்டம்', hi: 'हल्का-फुल्का घूमना या खड़े रहना' } },
      { value: 'strenuous', label: { en: 'Heavy physical labor / intense exercise', ta: 'கடுமையான உடல் உழைப்பு / உடற்பயிற்சி', hi: 'कड़ा शारीरिक श्रम / व्यायाम' } },
    ],
  },
  {
    id: 'AY-VIHARA-DAY-SLEEP-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'vihara',
    section: 'ayush_vihara',
    category: 'daily_routine',
    questionText: {
      en: 'Do you routinely sleep during the daytime after lunch?',
      ta: 'மதிய உணவுக்குப் பிறகு பகலில் தூங்கும் பழக்கம் உள்ளதா?',
      hi: 'क्या आपको दोपहर के खाने के बाद सोने की आदत है?',
    },
    answerType: 'yes_no',
    targetField: 'daytime_sleep_habit',
    priority: 75,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
  },
  {
    id: 'AY-VIHARA-SCREEN-001',
    version: '1.0',
    mode: 'ayush',
    complaint: 'vihara',
    section: 'ayush_vihara',
    category: 'daily_routine',
    questionText: {
      en: 'Do you spend long hours on mobile/computer screens right before sleeping at night?',
      ta: 'இரவில் தூங்கும் முன் பல மணி நேரம் மொபைல் போன் அல்லது கணினி பார்க்கும் பழக்கம் உள்ளதா?',
      hi: 'क्या आप रात में सोने से पहले देर तक मोबाइल या कंप्यूटर स्क्रीन देखते हैं?',
    },
    answerType: 'yes_no',
    targetField: 'night_screen_time',
    priority: 75,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    sourceType: 'patient_input',
  },
];
