import { ClinicalQuestion } from '../types';

export const ABDOMINAL_PAIN_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'GM-ABD-ONSET-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'abdominal_pain',
    section: 'history_of_present_illness',
    category: 'onset',
    questionText: {
      en: 'Did your stomach pain start suddenly or build up gradually?',
      ta: 'வயிறு வலி திடீரென்று ஆரம்பித்ததா அல்லது மெதுவாக அதிகரித்ததா?',
      hi: 'क्या पेट का दर्द अचानक शुरू हुआ या धीरे-धीरे बढ़ा?',
    },
    answerType: 'single_choice',
    targetField: 'onset_type',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      {
        value: 'sudden',
        label: { en: 'Sudden', ta: 'திடீரென்று', hi: 'अचानक' },
      },
      {
        value: 'gradual',
        label: { en: 'Gradual', ta: 'மெதுவாக', hi: 'धीरे-धीरे' },
      },
    ],
  },
  {
    id: 'GM-ABD-DURATION-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'abdominal_pain',
    section: 'history_of_present_illness',
    category: 'duration',
    questionText: {
      en: 'How long have you had this stomach pain?',
      ta: 'இந்த வயிறு வலி எவ்வளவு நாட்களாக அல்லது மணி நேரமாக இருக்கிறது?',
      hi: 'यह पेट दर्द कितने समय या कितने दिनों से हो रहा है?',
    },
    answerType: 'duration',
    targetField: 'duration_text',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-ABD-LOC-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'abdominal_pain',
    section: 'history_of_present_illness',
    category: 'location',
    questionText: {
      en: 'Which part of your stomach is hurting the most?',
      ta: 'வயிற்றின் எந்த பகுதியில் வலி அதிகமாக உள்ளது?',
      hi: 'पेट के किस हिस्से में सबसे ज्यादा दर्द हो रहा है?',
    },
    answerType: 'body_site',
    targetField: 'body_site',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'upper_center', label: { en: 'Upper middle (stomach area)', ta: 'மேல் வயிறு (நடுவில்)', hi: 'ऊपरी बीच का हिस्सा' } },
      { value: 'lower_right', label: { en: 'Lower right side', ta: 'கீழ் வயிறு (வலது பக்கம்)', hi: 'निचला दायां हिस्सा' } },
      { value: 'lower_left', label: { en: 'Lower left side', ta: 'கீழ் வயிறு (இடது பக்கம்)', hi: 'निचला बायां हिस्सा' } },
      { value: 'all_over', label: { en: 'All over the abdomen', ta: 'வயிறு முழுவதும்', hi: 'पूरे पेट में' } },
    ],
  },
  {
    id: 'GM-ABD-SEV-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'abdominal_pain',
    section: 'history_of_present_illness',
    category: 'severity',
    questionText: {
      en: 'On a scale of 1 to 10, how severe is your abdominal pain?',
      ta: '1 முதல் 10 வரையிலான அளவில் உங்கள் வயிறு வலி எவ்வளவு கடுமையானது?',
      hi: '1 से 10 के पैमाने पर आपका पेट दर्द कितना तेज है?',
    },
    answerType: 'numeric_scale',
    targetField: 'severity_score',
    priority: 80,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-ABD-FOOD-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'abdominal_pain',
    section: 'history_of_present_illness',
    category: 'aggravating_factors',
    questionText: {
      en: 'Does the pain get worse or better after eating food?',
      ta: 'உணவு சாப்பிட்ட பிறகு வலி அதிகமாகிறதா அல்லது குறைகிறதா?',
      hi: 'क्या खाना खाने के बाद दर्द बढ़ता है या कम होता है?',
    },
    answerType: 'single_choice',
    targetField: 'food_relation',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'worse_after_eating', label: { en: 'Worse after eating', ta: 'சாப்பிட்ட பிறகு அதிகமாகிறது', hi: 'खाने के बाद बढ़ता है' } },
      { value: 'better_after_eating', label: { en: 'Better after eating', ta: 'சாப்பிட்ட பிறகு குறைகிறது', hi: 'खाने के बाद आराम मिलता है' } },
      { value: 'no_relation', label: { en: 'No relation to food', ta: 'உணவோடு தொடர்பில்லை', hi: 'खाने से कोई संबंध नहीं' } },
    ],
  },
  {
    id: 'GM-ABD-BLOOD-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'abdominal_pain',
    section: 'history_of_present_illness',
    category: 'red_flag_screening',
    questionText: {
      en: 'Have you noticed any blood in your vomit or stool?',
      ta: 'வாந்தியிலோ அல்லது மலத்திலோ இரத்தம் ஏதேனும் வந்ததா?',
      hi: 'क्या आपको उल्टी या मल में खून दिखाई दिया है?',
    },
    answerType: 'yes_no',
    targetField: 'gastrointestinal_bleeding',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
  {
    id: 'GM-ABD-VOMIT-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'abdominal_pain',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Do you have nausea or repeated vomiting?',
      ta: 'உங்களுக்கு குமட்டல் அல்லது தொடர் வாந்தி உள்ளதா?',
      hi: 'क्या आपको जी मिचलाना या लगातार उल्टी होना महसूस हो रहा है?',
    },
    answerType: 'yes_no',
    targetField: 'associated_nausea_vomiting',
    priority: 85,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-ABD-BOWEL-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'abdominal_pain',
    section: 'history_of_present_illness',
    category: 'bowel',
    questionText: {
      en: 'Are you experiencing constipation, loose motions, or difficulty passing gas?',
      ta: 'உங்களுக்கு மலச்சிக்கல், வயிற்றுப்போக்கு அல்லது வாயு பிரியாமல் தவிப்பது போன்ற தொந்தரவு உள்ளதா?',
      hi: 'क्या आपको कब्ज, दस्त या गैस पास न होने की समस्या है?',
    },
    answerType: 'single_choice',
    targetField: 'bowel_disturbance',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'constipation', label: { en: 'Constipation', ta: 'மலச்சிக்கல்', hi: 'कब्ज' } },
      { value: 'diarrhea', label: { en: 'Loose motions', ta: 'வயிற்றுப்போக்கு', hi: 'दस्त' } },
      { value: 'bloating_gas', label: { en: 'Gas and bloating', ta: 'வயிறு உப்பசம் / வாயு', hi: 'गैस और अफारा' } },
    ],
  },
];
