import { ClinicalQuestion } from '../types';

export const BACK_PAIN_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'GM-BACK-DUR-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'back_pain',
    section: 'history_of_present_illness',
    category: 'duration',
    questionText: {
      en: 'How long have you had this back pain?',
      ta: 'இந்த முதுகு வலி எவ்வளவு நாட்களாக அல்லது மாதங்களாக இருக்கிறது?',
      hi: 'आपको कितने समय से पीठ दर्द हो रहा है?',
    },
    answerType: 'duration',
    targetField: 'duration_text',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-BACK-LOC-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'back_pain',
    section: 'history_of_present_illness',
    category: 'location',
    questionText: {
      en: 'Which part of your back is hurting?',
      ta: 'முதுகில் எந்த பகுதியில் வலி உள்ளது?',
      hi: 'पीठ के किस हिस्से में दर्द है?',
    },
    answerType: 'single_choice',
    targetField: 'body_site',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'lower_back', label: { en: 'Lower back (lumbar)', ta: 'இடுப்பு / கீழ் முதுகு', hi: 'निचली पीठ / कमर' } },
      { value: 'upper_back', label: { en: 'Upper back / shoulder blade area', ta: 'மேல் முதுகு / தோள்பட்டை', hi: 'ऊपरी पीठ' } },
      { value: 'neck_back', label: { en: 'Neck and upper back', ta: 'கழுத்து மற்றும் பிடரி', hi: 'गर्दन और ऊपरी हिस्सा' } },
    ],
  },
  {
    id: 'GM-BACK-RAD-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'back_pain',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Does the pain shoot down into your leg or cause numbness/tingling in your feet?',
      ta: 'வலி இடுப்பிலிருந்து கால் வரை பரவுகிறதா அல்லது கால்களில் மரத்துப்போவது போல் உள்ளதா?',
      hi: 'क्या दर्द कमर से होकर पैर की तरफ जाता है या पैर सुन्न महसूस होते हैं?',
    },
    answerType: 'yes_no',
    targetField: 'sciatica_radiculopathy',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-BACK-RED-FLAG-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'back_pain',
    section: 'history_of_present_illness',
    category: 'red_flag_screening',
    questionText: {
      en: 'Have you experienced loss of bladder or bowel control along with back pain?',
      ta: 'முதுகு வலியுடன் சேர்த்து சிறுநீர் அல்லது மலம் கட்டுப்பாடு இழப்பது போல் உள்ளதா?',
      hi: 'क्या पीठ दर्द के साथ पेशाब या मल का नियंत्रण खो गया है?',
    },
    answerType: 'yes_no',
    targetField: 'cauda_equina_red_flags',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
];
