import { ClinicalQuestion } from '../types';

export const BREATHLESSNESS_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'GM-SOB-ONSET-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'breathlessness',
    section: 'history_of_present_illness',
    category: 'onset',
    questionText: {
      en: 'Did your breathing difficulty start suddenly or develop gradually?',
      ta: 'மூச்சு வாங்குதல் திடீரென்று ஆரம்பித்ததா அல்லது மெதுவாக அதிகரித்ததா?',
      hi: 'क्या सांस लेने में तकलीफ अचानक शुरू हुई या धीरे-धीरे बढ़ी?',
    },
    answerType: 'single_choice',
    targetField: 'onset_type',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
    choices: [
      { value: 'sudden', label: { en: 'Sudden', ta: 'திடீரென்று', hi: 'अचानक' } },
      { value: 'gradual', label: { en: 'Gradual', ta: 'மெதுவாக', hi: 'धीरे-धीरे' } },
    ],
  },
  {
    id: 'GM-SOB-DURATION-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'breathlessness',
    section: 'history_of_present_illness',
    category: 'duration',
    questionText: {
      en: 'How long have you felt short of breath?',
      ta: 'எவ்வளவு நாட்களாக மூச்சுத்திணறல் இருக்கிறது?',
      hi: 'आपको कितने समय से सांस फूलने की समस्या महसूस हो रही है?',
    },
    answerType: 'duration',
    targetField: 'duration_text',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-SOB-EXERTION-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'breathlessness',
    section: 'history_of_present_illness',
    category: 'severity',
    questionText: {
      en: 'Does breathlessness occur when walking, or even while sitting at rest?',
      ta: 'நடக்கும் போது மூச்சு வாங்குகிறதா அல்லது சும்மா உட்கார்ந்திருக்கும் போது கூட மூச்சு வாங்குமா?',
      hi: 'क्या सांस चलने पर फूलती है या बैठे-बैठे आराम की हालत में भी फूलती है?',
    },
    answerType: 'single_choice',
    targetField: 'exertion_level',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
    choices: [
      { value: 'at_rest', label: { en: 'Even while resting (Severe)', ta: 'சும்மா இருக்கும் போது கூட (கடுமையானது)', hi: 'बैठे-बैठे भी (गंभीर)' } },
      { value: 'minimal_exertion', label: { en: 'With light walking inside house', ta: 'வீட்டுக்குள் லேசாக நடக்கும் போது', hi: 'घर में थोड़ा चलने पर' } },
      { value: 'strenuous_exertion', label: { en: 'Only with fast walking or stairs', ta: 'வேகமாக நடக்கும் போது / படிக்கட்டு ஏறும் போது', hi: 'तेज चलने या सीढ़ी चढ़ने पर' } },
    ],
  },
  {
    id: 'GM-SOB-ORTHOPNEA-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'breathlessness',
    section: 'history_of_present_illness',
    category: 'timing',
    questionText: {
      en: 'Do you need to prop yourself up with extra pillows to sleep comfortably at night?',
      ta: 'இரவில் நிம்மதியாக தூங்க பல தலையணைகளை வைத்து உயரப்படுத்த வேண்டுமா?',
      hi: 'क्या रात में सोने के लिए extra तकिये लगाने की जरूरत पड़ती है?',
    },
    answerType: 'yes_no',
    targetField: 'orthopnea',
    priority: 85,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-SOB-EDEMA-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'breathlessness',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Have you noticed any swelling in your feet, ankles, or legs?',
      ta: 'உங்கள் பாதங்கள் அல்லது கால்களில் வீக்கம் ஏதேனும் உள்ளதா?',
      hi: 'क्या आपके पैरों या टखनों में सूजन आई है?',
    },
    answerType: 'yes_no',
    targetField: 'associated_pedal_edema',
    priority: 85,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
];
