import { ClinicalQuestion } from '../types';

export const CHEST_PAIN_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'GM-CP-ONSET-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'chest_pain',
    section: 'history_of_present_illness',
    category: 'onset',
    questionText: {
      en: 'Did the chest pain start suddenly or come on gradually?',
      ta: 'நெஞ்சு வலி திடீரென்று ஆரம்பித்ததா அல்லது மெதுவாக அதிகரித்ததா?',
      hi: 'क्या सीने का दर्द अचानक शुरू हुआ या धीरे-धीरे बढ़ा?',
    },
    answerType: 'single_choice',
    targetField: 'onset_type',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      {
        value: 'sudden',
        label: {
          en: 'Sudden',
          ta: 'திடீரென்று',
          hi: 'अचानक',
        },
      },
      {
        value: 'gradual',
        label: {
          en: 'Gradual',
          ta: 'மெதுவாக',
          hi: 'धीरे-धीरे',
        },
      },
    ],
  },
  {
    id: 'GM-CP-DURATION-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'chest_pain',
    section: 'history_of_present_illness',
    category: 'duration',
    questionText: {
      en: 'How long have you had this chest pain?',
      ta: 'இந்த நெஞ்சு வலி எவ்வளவு நேரமாக அல்லது எத்தணை நாட்களாக இருக்கிறது?',
      hi: 'यह सीने का दर्द कितने समय या कितने दिनों से हो रहा है?',
    },
    answerType: 'duration',
    targetField: 'duration_text',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    examples: {
      en: 'For 2 days, 30 minutes, 1 hour',
      ta: '2 நாட்களாக, 30 நிமிடங்களாக',
      hi: '2 दिनों से, 30 मिनट से',
    },
  },
  {
    id: 'GM-CP-LOC-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'chest_pain',
    section: 'history_of_present_illness',
    category: 'location',
    questionText: {
      en: 'Where exactly in your chest do you feel the pain?',
      ta: 'மார்பில் எந்த இடத்தில் வலி உணர்கிறீர்கள்?',
      hi: 'सीने में ठीक किस जगह दर्द महसूस हो रहा है?',
    },
    answerType: 'body_site',
    targetField: 'body_site',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      {
        value: 'center',
        label: {
          en: 'Center of chest',
          ta: 'மார்பின் நடுவில்',
          hi: 'सीने के बीच में',
        },
      },
      {
        value: 'left',
        label: {
          en: 'Left side of chest',
          ta: 'மார்பின் இடது பக்கம்',
          hi: 'सीने के बाईं तरफ',
        },
      },
      {
        value: 'right',
        label: {
          en: 'Right side of chest',
          ta: 'மார்பின் வலது பக்கம்',
          hi: 'सीने के दाईं तरफ',
        },
      },
    ],
  },
  {
    id: 'GM-CP-CHAR-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'chest_pain',
    section: 'history_of_present_illness',
    category: 'character',
    questionText: {
      en: 'How would you describe the feeling of the pain?',
      ta: 'இந்த வலி எப்படிப்பட்ட உணர்வாக இருக்கிறது?',
      hi: 'दर्द का अहसास कैसा है?',
    },
    answerType: 'single_choice',
    targetField: 'character_quality',
    priority: 85,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      {
        value: 'pressure_heaviness',
        label: {
          en: 'Heavy pressure or squeezing',
          ta: 'பாரமாக அழுத்துவது போல்',
          hi: 'भारी दबाव या जकड़न जैसा',
        },
      },
      {
        value: 'sharp_stabbing',
        label: {
          en: 'Sharp or stabbing',
          ta: 'குத்துவது போன்ற கூர்மையான வலி',
          hi: 'तेज या चुभने वाला दर्द',
        },
      },
      {
        value: 'burning',
        label: {
          en: 'Burning sensation',
          ta: 'எரிச்சல் உணர்வு',
          hi: 'जलन जैसा दर्द',
        },
      },
      {
        value: 'tightness',
        label: {
          en: 'Tightness or constriction',
          ta: 'இறுக்கிப் பிடிப்பது போல்',
          hi: 'कसने जैसा दर्द',
        },
      },
    ],
  },
  {
    id: 'GM-CP-SEV-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'chest_pain',
    section: 'history_of_present_illness',
    category: 'severity',
    questionText: {
      en: 'On a scale of 1 to 10, how severe is your chest pain?',
      ta: '1 முதல் 10 வரையிலான அளவில் உங்கள் வலி எவ்வளவு கடுமையானது?',
      hi: '1 से 10 के पैमाने पर आपका दर्द कितना तेज है?',
    },
    answerType: 'numeric_scale',
    targetField: 'severity_score',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-CP-EXERTION-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'chest_pain',
    section: 'history_of_present_illness',
    category: 'aggravating_factors',
    questionText: {
      en: 'Does the pain get worse when you walk, climb stairs, or exert yourself?',
      ta: 'வேகமாக நடக்கும் போதோ அல்லது படிக்கட்டுகளில் ஏறும் போதோ வலி அதிகமாகிறதா?',
      hi: 'क्या चलने, सीढ़ियां चढ़ने या मेहनत करने पर दर्द बढ़ता है?',
    },
    answerType: 'yes_no',
    targetField: 'aggravating_factors',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-CP-REST-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'chest_pain',
    section: 'history_of_present_illness',
    category: 'relieving_factors',
    questionText: {
      en: 'Does resting or sitting down ease the pain?',
      ta: 'அமர்ந்து ஓய்வு எடுத்தால் வலி குறைகிறதா?',
      hi: 'क्या बैठने या आराम करने पर दर्द में आराम मिलता है?',
    },
    answerType: 'yes_no',
    targetField: 'relieving_factors',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-CP-RADIATION-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'chest_pain',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Does the pain spread to your left arm, shoulder, neck, jaw, or back?',
      ta: 'இந்த வலி உங்கள் இடது கை, தோள்பட்டை, கழுத்து அல்லது தாடைக்கு பரவுகிறதா?',
      hi: 'क्या यह दर्द आपके बाएं हाथ, कंधे, गर्दन, जबड़े या पीठ की तरफ फैलता है?',
    },
    answerType: 'yes_no',
    targetField: 'radiation_site',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
  {
    id: 'GM-CP-SOB-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'chest_pain',
    section: 'history_of_present_illness',
    category: 'red_flag_screening',
    questionText: {
      en: 'Do you also have severe shortness of breath or difficulty breathing?',
      ta: 'உங்களுக்கு அதிக மூச்சுத்திணறல் அல்லது மூச்சு வாங்குதல் உள்ளதா?',
      hi: 'क्या आपको बहुत ज्यादा सांस फूलने या सांस लेने में तकलीफ भी हो रही है?',
    },
    answerType: 'yes_no',
    targetField: 'associated_shortness_of_breath',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
  {
    id: 'GM-CP-SWEAT-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'chest_pain',
    section: 'history_of_present_illness',
    category: 'red_flag_screening',
    questionText: {
      en: 'Are you experiencing heavy sweating or feeling cold and clammy?',
      ta: 'உங்களுக்கு அதிக வியர்வை அல்லது உடல் குளிர்ந்து போகும் உணர்வு உள்ளதா?',
      hi: 'क्या आपको बहुत ज्यादा पसीना आ रहा है या ठिठुरन महसूस हो रही है?',
    },
    answerType: 'yes_no',
    targetField: 'associated_sweating',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
  {
    id: 'GM-CP-DIZZY-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'chest_pain',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Do you feel dizzy, lightheaded, or feel like you might faint?',
      ta: 'உங்களுக்கு தலைச்சுற்றல் அல்லது மயக்கம் வருவது போல் உள்ளதா?',
      hi: 'क्या आपको चक्कर आ रहे हैं या बेहोशी जैसा महसूस हो रहा है?',
    },
    answerType: 'yes_no',
    targetField: 'associated_dizziness',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
];
