import { ClinicalQuestion } from '../types';

export const COMMON_HISTORY_QUESTIONS: ClinicalQuestion[] = [
  // PAST MEDICAL HISTORY (PMH)
  {
    id: 'GM-HIST-PMH-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'common_history',
    section: 'past_medical_history',
    category: 'past_medical_history',
    questionText: {
      en: 'Do you have a history of any chronic health conditions like High BP, Diabetes, or Asthma?',
      ta: 'உங்களுக்கு உயர் இரத்த அழுத்தம், சர்க்கரை நோய் அல்லது ஆஸ்துமா போன்ற நீண்டகால நோய்கள் உள்ளனவா?',
      hi: 'क्या आपको हाई बीपी, डायबिटीज या अस्थमा जैसी कोई पुरानी बीमारी है?',
    },
    answerType: 'multi_choice',
    targetField: 'past_medical_history',
    priority: 85,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'hypertension', label: { en: 'High Blood Pressure (Hypertension)', ta: 'உயர் இரத்த அழுத்தம் (பிபி)', hi: 'हाई ब्लड प्रेशर (बीपी)' } },
      { value: 'diabetes', label: { en: 'Diabetes (Sugar)', ta: 'சர்க்கரை நோய்', hi: 'डायबिटीज (शुगर)' } },
      { value: 'heart_disease', label: { en: 'Heart Condition / Previous Heart Attack', ta: 'இதய நோய்', hi: 'दिल की बीमारी' } },
      { value: 'asthma_copd', label: { en: 'Asthma / Breathing Problem', ta: 'ஆஸ்துமா / மூச்சு பிரச்சனை', hi: 'अस्थमा / सांस की बीमारी' } },
      { value: 'kidney_disease', label: { en: 'Kidney Disease', ta: 'சிறுநீரக நோய்', hi: 'गुर्दे (किडनी) की बीमारी' } },
      { value: 'none', label: { en: 'No chronic conditions', ta: 'எதுவும் இல்லை', hi: 'कोई बीमारी नहीं' } },
    ],
  },
  {
    id: 'GM-HIST-SURGERY-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'common_history',
    section: 'past_medical_history',
    category: 'past_medical_history',
    questionText: {
      en: 'Have you had any previous surgeries or major hospital admissions?',
      ta: 'முன்பு ஏதேனும் அறுவை சிகிச்சை அல்லது மருத்துவமனையில் அனுமதிக்கப்பட்டது உண்டா?',
      hi: 'क्या आपकी पहले कोई सर्जरी या बड़ी अस्पताल में भर्ती हुई है?',
    },
    answerType: 'yes_no',
    targetField: 'surgical_history',
    priority: 75,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },

  // MEDICATION HISTORY
  {
    id: 'GM-HIST-MEDS-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'common_history',
    section: 'medication_history',
    category: 'medication_history',
    questionText: {
      en: 'Are you currently taking any daily medicines or tablets?',
      ta: 'நீங்கள் தினமும் சாப்பிடும் மருந்துகள் அல்லது மாத்திரைகள் ஏதேனும் உள்ளனவா?',
      hi: 'क्या आप फिलहाल रोजाना कोई दवाई या गोली ले रहे हैं?',
    },
    answerType: 'free_text',
    targetField: 'current_medications',
    priority: 85,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    examples: {
      en: 'Metformin 500mg, Amlodipine 5mg daily',
      ta: 'பிபி மாத்திரை, சர்க்கரை மாத்திரை தினமும்',
      hi: 'मेटफॉर्मिन 500mg, एम्लोडिपिन 5mg',
    },
  },

  // ALLERGY HISTORY
  {
    id: 'GM-HIST-ALLERGY-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'common_history',
    section: 'allergy_history',
    category: 'allergy_history',
    questionText: {
      en: 'Do you have any known allergies to medicines or foods?',
      ta: 'உங்களுக்கு ஏதேனும் மருந்து அல்லது உணவு அலர்ஜி உள்ளதா?',
      hi: 'क्या आपको किसी दवा या खाने से कोई एलर्जी है?',
    },
    answerType: 'yes_no',
    targetField: 'allergies',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },

  // FAMILY HISTORY
  {
    id: 'GM-HIST-FAMILY-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'common_history',
    section: 'family_history',
    category: 'family_history',
    questionText: {
      en: 'Is there a family history of heart disease, diabetes, or stroke in your parents or siblings?',
      ta: 'உங்கள் பெற்றோர் அல்லது உடன் பிறந்தவர்களுக்கு இதய நோய், சர்க்கரை நோய் அல்லது பக்கவாதம் இருந்ததா?',
      hi: 'क्या आपके माता-पिता या भाई-बहनों में दिल की बीमारी, शुगर या स्ट्रोक का इतिहास है?',
    },
    answerType: 'multi_choice',
    targetField: 'family_history',
    priority: 75,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'father_heart', label: { en: 'Father had heart disease / stroke', ta: 'தந்தைக்கு இதய நோய் / பக்கவாதம்', hi: 'पिता को दिल की बीमारी / स्ट्रोक' } },
      { value: 'mother_diabetes', label: { en: 'Mother had diabetes', ta: 'தாயாருக்கு சர்க்கரை நோய்', hi: 'माताजी को शुगर' } },
      { value: 'none', label: { en: 'No family history', ta: 'எதுவும் இல்லை', hi: 'कोई पारिवारिक इतिहास नहीं' } },
    ],
  },

  // SOCIAL HISTORY & LIFESTYLE
  {
    id: 'GM-HIST-TOBACCO-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'common_history',
    section: 'social_history',
    category: 'tobacco',
    questionText: {
      en: 'Do you use tobacco products or smoke bidis/cigarettes?',
      ta: 'புகையிலை பொருட்கள், பீடி அல்லது சிகரெட் உபயோகிக்கும் பழக்கம் உள்ளதா?',
      hi: 'क्या आप तंबाकू, बीड़ी या सिगरेट का सेवन करते हैं?',
    },
    answerType: 'single_choice',
    targetField: 'tobacco_use',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'daily_smoker', label: { en: 'Smoke daily (bidi / cigarette)', ta: 'தினமும் பீடி/சிகரெட் குடிப்பேன்', hi: 'रोज बीड़ी/सिगरेट पीते हैं' } },
      { value: 'tobacco_chewer', label: { en: 'Chew tobacco daily', ta: 'தினமும் புகையிலை மெல்லுவேன்', hi: 'रोज तंबाकू चबाते हैं' } },
      { value: 'never', label: { en: 'Never used tobacco', ta: 'உபயோகித்தது இல்லை', hi: 'कभी नहीं किया' } },
    ],
  },
  {
    id: 'GM-HIST-ALCOHOL-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'common_history',
    section: 'social_history',
    category: 'alcohol',
    questionText: {
      en: 'Do you consume alcohol?',
      ta: 'மது அருந்தும் பழக்கம் உள்ளதா?',
      hi: 'क्या आप शराब का सेवन करते हैं?',
    },
    answerType: 'single_choice',
    targetField: 'alcohol_use',
    priority: 75,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'regular', label: { en: 'Regularly', ta: 'தவறாமல்', hi: 'नियमित रूप से' } },
      { value: 'occasional', label: { en: 'Occasionally', ta: 'எப்போதாவது', hi: 'कभी-कभार' } },
      { value: 'never', label: { en: 'Never', ta: 'இல்லை', hi: 'कभी नहीं' } },
    ],
  },
  {
    id: 'GM-HIST-WORK-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'common_history',
    section: 'social_history',
    category: 'occupation',
    questionText: {
      en: 'What is your current occupation or type of daily work?',
      ta: 'நீங்கள் என்ன வேலை செய்கிறீர்கள்?',
      hi: 'आपका वर्तमान व्यवसाय या काम क्या है?',
    },
    answerType: 'free_text',
    targetField: 'occupation',
    priority: 75,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    examples: {
      en: 'Construction labor, Desk computer job, Farming, Shopkeeper',
      ta: 'கட்டிட வேலை, கணினி வேலை, விவசாயம்',
      hi: 'दुकानदार, मजदूरी, कंप्यूटर जॉब',
    },
  },
  {
    id: 'GM-HIST-SLEEP-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'common_history',
    section: 'lifestyle',
    category: 'sleep',
    questionText: {
      en: 'How many hours of sleep do you get per night on average?',
      ta: 'இரவில் சராசரியாக எத்தனை மணி நேரம் தூங்குகிறீர்கள்?',
      hi: 'औसतन आप रात में कितने घंटे सोते हैं?',
    },
    answerType: 'numeric',
    targetField: 'sleep_hours',
    priority: 75,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    examples: { en: '5 hours, 7 hours', ta: '5 மணி நேரம்', hi: '6 घंटे' },
  },
];
