import { ClinicalQuestion } from '../types';

export const COUGH_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'GM-COUGH-DUR-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'cough',
    section: 'history_of_present_illness',
    category: 'duration',
    questionText: {
      en: 'How long have you had this cough?',
      ta: 'இந்த இருமல் எவ்வளவு நாட்களாக இருக்கிறது?',
      hi: 'यह खांसी कितने दिनों से हो रही है?',
    },
    answerType: 'duration',
    targetField: 'duration_text',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-COUGH-TYPE-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'cough',
    section: 'history_of_present_illness',
    category: 'character',
    questionText: {
      en: 'Is it a dry cough or do you bring up phlegm/sputum?',
      ta: 'இது வறட்டு இருமலா அல்லது சளி வருகிறதா?',
      hi: 'क्या यह सूखी खांसी है या बलगम आता है?',
    },
    answerType: 'single_choice',
    targetField: 'cough_type',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'dry', label: { en: 'Dry cough', ta: 'வறட்டு இருமல்', hi: 'सूखी खांसी' } },
      { value: 'productive', label: { en: 'Cough with phlegm/sputum', ta: 'சளி வரும் இருமல்', hi: 'बलगम वाली खांसी' } },
    ],
  },
  {
    id: 'GM-COUGH-BLOOD-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'cough',
    section: 'history_of_present_illness',
    category: 'red_flag_screening',
    questionText: {
      en: 'Have you noticed any blood in your sputum/phlegm?',
      ta: 'சளியில் இரத்தம் ஏதேனும் வருகிறதா?',
      hi: 'क्या बलगम में खून दिखाई दिया है?',
    },
    answerType: 'yes_no',
    targetField: 'hemoptysis',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
  {
    id: 'GM-COUGH-NIGHT-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'cough',
    section: 'history_of_present_illness',
    category: 'timing',
    questionText: {
      en: 'Is the cough worse at night or when lying down?',
      ta: 'இரவில் அல்லது படுக்கும் போது இருமல் அதிகமாகிறதா?',
      hi: 'क्या रात में या लेटने पर खांसी ज्यादा होती है?',
    },
    answerType: 'yes_no',
    targetField: 'nocturnal_cough',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-COUGH-WHEEZE-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'cough',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Do you hear a whistling sound (wheezing) when you breathe?',
      ta: 'மூச்சு விடும்போது நெஞ்சில் விசிலடிப்பது போல் (வொயீசிங்) சத்தம் கேட்கிறதா?',
      hi: 'क्या सांस लेते समय सीटी जैसी आवाज (व्हीजिंग) आती है?',
    },
    answerType: 'yes_no',
    targetField: 'associated_wheezing',
    priority: 85,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
];
