import { ClinicalQuestion } from '../types';

export const DIARRHEA_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'GM-DIA-DUR-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'diarrhea',
    section: 'history_of_present_illness',
    category: 'duration',
    questionText: {
      en: 'How many days have you had loose motions?',
      ta: 'எத்தனை நாட்களாக வயிற்றுப்போக்கு இருக்கிறது?',
      hi: 'आपको कितने दिनों से दस्त हो रहे हैं?',
    },
    answerType: 'duration',
    targetField: 'duration_text',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-DIA-FREQ-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'diarrhea',
    section: 'history_of_present_illness',
    category: 'frequency',
    questionText: {
      en: 'How many times have you passed loose stool today?',
      ta: 'இன்று எத்தனை முறை கழிவறை போக வேண்டி இருந்தது?',
      hi: 'आज कितनी बार दस्त हुए हैं?',
    },
    answerType: 'numeric',
    targetField: 'stool_frequency',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-DIA-BLOOD-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'diarrhea',
    section: 'history_of_present_illness',
    category: 'red_flag_screening',
    questionText: {
      en: 'Have you noticed any blood or mucus in your stool?',
      ta: 'மலத்தில் இரத்தம் அல்லது வழவழப்பான சளி ஏதேனும் வருகிறதா?',
      hi: 'क्या दस्त में खून या आंव (बलगम) आ रहा है?',
    },
    answerType: 'yes_no',
    targetField: 'dysentery_blood_in_stool',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
  {
    id: 'GM-DIA-DEHYDRATION-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'diarrhea',
    section: 'history_of_present_illness',
    category: 'red_flag_screening',
    questionText: {
      en: 'Are you feeling extremely thirsty, dry-mouthed, or passing very little urine?',
      ta: 'உங்களுக்கு அதிக தாகம், வாய் உலர்ந்து போதல் அல்லது சிறுநீர் மிகக் குறைவாகப் போதல் உள்ளதா?',
      hi: 'क्या आपको बहुत ज्यादा प्यास, मुंह सूखना या बहुत कम पेशाब होना महसूस हो रहा है?',
    },
    answerType: 'yes_no',
    targetField: 'dehydration_symptoms',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
];
