import { ClinicalQuestion } from '../types';

export const DIZZINESS_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'GM-DIZ-TYPE-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'dizziness',
    section: 'history_of_present_illness',
    category: 'character',
    questionText: {
      en: 'What do you feel when you say dizzy? Does the room spin around, or do you feel like you might pass out?',
      ta: 'தலைசுற்றல் என்று கூறும்போது சுற்றியுள்ள பொருட்கள் சுழல்வது போல் உள்ளதா அல்லது மயக்கம் வருவது போல் உள்ளதா?',
      hi: 'चक्कर आने से आपका क्या मतलब है? क्या कमरा घूमता हुआ लगता है या ऐसा लगता है कि आप बेहोश हो जाएंगे?',
    },
    answerType: 'single_choice',
    targetField: 'dizziness_character',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'vertigo_spinning', label: { en: 'Room spinning around (Vertigo)', ta: 'சுற்றியுள்ள இடம் சுழல்வது போல் (வெர்டிகோ)', hi: 'कमरा घूमना (चक्कर)' } },
      { value: 'presyncope_faint', label: { en: 'Feeling about to pass out / blacking out', ta: 'கண் இருட்டி மயக்கம் வருவது போல்', hi: 'आंखों के आगे अंधेरा या बेहोशी जैसा' } },
      { value: 'unsteadiness_balance', label: { en: 'Loss of balance while walking', ta: 'நடக்கும் போது நிலைதடுமாறுவது', hi: 'चलते समय संतुलन बिगड़ना' } },
    ],
  },
  {
    id: 'GM-DIZ-DUR-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'dizziness',
    section: 'history_of_present_illness',
    category: 'duration',
    questionText: {
      en: 'How long have you had this dizziness?',
      ta: 'எவ்வளவு நாட்களாக இந்த தலைச்சுற்றல் தொந்தரவு உள்ளது?',
      hi: 'आपको कितने समय से चक्कर आ रहे हैं?',
    },
    answerType: 'duration',
    targetField: 'duration_text',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-DIZ-TRIGGERS-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'dizziness',
    section: 'history_of_present_illness',
    category: 'aggravating_factors',
    questionText: {
      en: 'Does the dizziness happen when standing up suddenly, turning your head, or walking in the sun?',
      ta: 'திடீரென்று எழுந்திருக்கும் போதோ, தலையை திருப்பும் போதோ அல்லது வெயிலில் நடக்கும் போதோ தலைசுற்றுகிறதா?',
      hi: 'क्या अचानक खड़े होने, सिर घुमाने या धूप में चलने पर चक्कर आते हैं?',
    },
    answerType: 'single_choice',
    targetField: 'dizziness_trigger',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'postural_standing', label: { en: 'When standing up from sitting/lying', ta: 'உட்கார்ந்து/படுத்து எழும் போது', hi: 'लेटे या बैठे से खड़े होने पर' } },
      { value: 'head_movement', label: { en: 'When turning head in bed', ta: 'தலையை பக்கவாட்டில் திருப்பும் போது', hi: 'सिर घुमाने पर' } },
      { value: 'sun_heat', label: { en: 'Walking in sun or heat', ta: 'வெயிலில் நடக்கும் போது', hi: 'धूप या गर्मी में चलने पर' } },
    ],
  },
  {
    id: 'GM-DIZ-EARS-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'dizziness',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Do you hear ringing sounds in your ears (tinnitus) or reduced hearing during dizziness?',
      ta: 'தலைச்சுற்றலின் போது காதில் ரின்னு சத்தம் (டினிடஸ்) அல்லது கேட்கும் திறன் குறைவது உள்ளதா?',
      hi: 'क्या चक्कर के साथ कानों में घंटी जैसी आवाजें (टिनिटस) या कम सुनाई देता है?',
    },
    answerType: 'yes_no',
    targetField: 'associated_tinnitus',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-DIZ-SYNCOPE-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'dizziness',
    section: 'history_of_present_illness',
    category: 'red_flag_screening',
    questionText: {
      en: 'Have you actually fainted or lost consciousness?',
      ta: 'உங்களுக்கு உண்மையாகவே மயக்கம் அடைந்து நினைவு தப்பியது உண்டா?',
      hi: 'क्या आप सचमुच बेहोश हुए हैं या चेतना खोई है?',
    },
    answerType: 'yes_no',
    targetField: 'syncope_loss_of_consciousness',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
];
