import { ClinicalQuestion } from '../types';

export const FATIGUE_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'GM-FAT-DUR-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'fatigue',
    section: 'history_of_present_illness',
    category: 'duration',
    questionText: {
      en: 'How long have you been feeling constantly tired or weak?',
      ta: 'எவ்வளவு நாட்களாக அல்லது மாதங்களாக அதிக சோர்வு மற்றும் பலவீனம் உள்ளது?',
      hi: 'आपको कितने समय से लगातार थकान या कमजोरी महसूस हो रही है?',
    },
    answerType: 'duration',
    targetField: 'duration_text',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-FAT-WEIGHT-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'fatigue',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Have you experienced unexpected weight loss or loss of appetite?',
      ta: 'எதிர்பாராத உடல் எடைக் குறைவு அல்லது பசியின்மை ஏதேனும் உள்ளதா?',
      hi: 'क्या आपका वजन अचानक कम हुआ है या भूख कम लग रही है?',
    },
    answerType: 'yes_no',
    targetField: 'unintentional_weight_loss',
    priority: 85,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-FAT-SLEEP-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'fatigue',
    section: 'history_of_present_illness',
    category: 'sleep',
    questionText: {
      en: 'Do you feel refreshed after sleeping, or do you wake up feeling unrefreshed?',
      ta: 'தூங்கி எழுந்தவுடன் புத்துணர்ச்சியாக உணர்கிறீர்களா அல்லது அப்போதும் சோர்வாகவே உள்ளதா?',
      hi: 'क्या सोने के बाद आप तरोताजा महसूस करते हैं या उठने पर भी थकान बनी रहती है?',
    },
    answerType: 'single_choice',
    targetField: 'sleep_quality_fatigue',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'refreshed', label: { en: 'Refreshed', ta: 'புத்துணர்ச்சியாக', hi: 'तरोताजा' } },
      { value: 'unrefreshed', label: { en: 'Unrefreshed / still tired', ta: 'சோர்வாகவே உள்ளது', hi: 'उठने पर भी थकान रहती है' } },
    ],
  },
  {
    id: 'GM-FAT-IMPACT-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'fatigue',
    section: 'history_of_present_illness',
    category: 'progression',
    questionText: {
      en: 'Does this tiredness interfere with your daily routine or work?',
      ta: 'இந்த சோர்வு உங்கள் தினசரி வேலைகளை செய்வதில் பாதிப்பை ஏற்படுத்துகிறதா?',
      hi: 'क्या यह थकान आपके रोजमर्रा के काम या नौकरी में रुकावट डाल रही है?',
    },
    answerType: 'yes_no',
    targetField: 'fatigue_daily_impact',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
];
