import { ClinicalQuestion } from '../types';

export const FEVER_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'GM-FEV-DURATION-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'fever',
    section: 'history_of_present_illness',
    category: 'duration',
    questionText: {
      en: 'How many days have you had fever?',
      ta: 'எத்தனை நாட்களாக காய்ச்சல் இருக்கிறது?',
      hi: 'आपको कितने दिनों से बुखार है?',
    },
    answerType: 'duration',
    targetField: 'duration_text',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-FEV-TEMP-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'fever',
    section: 'history_of_present_illness',
    category: 'severity',
    questionText: {
      en: 'Have you measured your temperature? If yes, what was the highest reading?',
      ta: 'காய்ச்சலை அளந்து பார்த்தீர்களா? பார்த்திருந்தால் அதிகபட்சம் எவ்வளவு இருந்தது?',
      hi: 'क्या आपने तापमान नापा है? यदि हां, तो सबसे ज्यादा कितना था?',
    },
    answerType: 'numeric',
    targetField: 'measured_temperature',
    priority: 85,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    examples: { en: '101 F, 102.5 F, 38.5 C', ta: '101 ஃபாரன்ஹீட்', hi: '101 बुखार' },
  },
  {
    id: 'GM-FEV-CHILLS-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'fever',
    section: 'history_of_present_illness',
    category: 'character',
    questionText: {
      en: 'Do you experience severe chills or shivering with the fever?',
      ta: 'காய்ச்சல் வரும் போது குளிர் நடுக்கம் அல்லது உடல் நடுங்குவது போல் உள்ளதா?',
      hi: 'क्या बुखार के साथ बहुत ठंड या ककंपकंपी महसूस होती है?',
    },
    answerType: 'yes_no',
    targetField: 'chills_rigors',
    priority: 85,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-FEV-RESP-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'fever',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Do you have cough, sore throat, or difficulty breathing?',
      ta: 'உங்களுக்கு இருமல், தொண்டை வலி அல்லது மூச்சு வாங்குதல் உள்ளதா?',
      hi: 'क्या आपको खांसी, गले में खराश या सांस लेने में तकलीफ है?',
    },
    answerType: 'yes_no',
    targetField: 'associated_respiratory_symptoms',
    priority: 85,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-FEV-URINARY-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'fever',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Do you feel burning or pain when passing urine?',
      ta: 'நீர் கழிக்கையில் எரிச்சல் அல்லது வலி உள்ளதா?',
      hi: 'क्या पेशाब करते समय जलन या दर्द होता है?',
    },
    answerType: 'yes_no',
    targetField: 'associated_dysuria',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-FEV-RASH-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'fever',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Have you noticed any red spots, skin rash, or body ache?',
      ta: 'உடலில் சிவப்பாக தடிப்புகள், தழும்புகள் அல்லது கடுமையான உடல் வலி உள்ளதா?',
      hi: 'क्या शरीर पर चकत्ते, लाल दाने या तेज बदन दर्द है?',
    },
    answerType: 'yes_no',
    targetField: 'associated_rash_bodyache',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-FEV-RED-FLAG-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'fever',
    section: 'history_of_present_illness',
    category: 'red_flag_screening',
    questionText: {
      en: 'Are you feeling very drowsy, confused, or experiencing shortness of breath?',
      ta: 'உங்களுக்கு அதிக மயக்கம், மன குழப்பம் அல்லது மூச்சுத்திணறல் உள்ளதா?',
      hi: 'क्या आपको बहुत ज्यादा सुस्ती, भ्रम या सांस लेने में परेशानी हो रही है?',
    },
    answerType: 'yes_no',
    targetField: 'fever_red_flags',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
];
