import { ClinicalQuestion } from '../types';

export const HEADACHE_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'GM-HA-ONSET-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'headache',
    section: 'history_of_present_illness',
    category: 'onset',
    questionText: {
      en: 'Did this headache start suddenly with maximum pain in seconds, or did it build up gradually?',
      ta: 'இந்த தலைவலி திடீரென்று நொடடிகளில் உச்சக்கட்டமாக வந்ததா அல்லது மெதுவாக அதிகரித்ததா?',
      hi: 'क्या यह सिरदर्द अचानक कुछ ही सेकंड में बहुत तेज हो गया या धीरे-धीरे बढ़ा?',
    },
    answerType: 'single_choice',
    targetField: 'onset_type',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
    choices: [
      { value: 'thunderclap_sudden', label: { en: 'Sudden severe (thunderclap)', ta: 'திடீரென்று கடுமையான வலி', hi: 'अचानक बहुत तेज' } },
      { value: 'gradual', label: { en: 'Gradual build up', ta: 'மெதுவாக அதிகரித்தது', hi: 'धीरे-धीरे बढ़ा' } },
    ],
  },
  {
    id: 'GM-HA-DURATION-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'headache',
    section: 'history_of_present_illness',
    category: 'duration',
    questionText: {
      en: 'How long has this headache lasted?',
      ta: 'இந்த தலைவலி எவ்வளவு நேரமாக இருக்கிறது?',
      hi: 'यह सिरदर्द कितने समय से हो रहा है?',
    },
    answerType: 'duration',
    targetField: 'duration_text',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-HA-LOC-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'headache',
    section: 'history_of_present_illness',
    category: 'location',
    questionText: {
      en: 'Where is the pain located?',
      ta: 'தலையில் எந்த பகுதியில் வலி உள்ளது?',
      hi: 'सिर में किस जगह दर्द है?',
    },
    answerType: 'single_choice',
    targetField: 'body_site',
    priority: 80,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'one_side', label: { en: 'One side of head', ta: 'தலையின் ஒரு பக்கம்', hi: 'सिर की एक तरफ' } },
      { value: 'both_sides', label: { en: 'Both sides of head', ta: 'தலையின் இரு பக்கமும்', hi: 'सिर की दोनों तरफ' } },
      { value: 'forehead', label: { en: 'Forehead area', ta: 'நெற்றி பகுதி', hi: 'माथे पर' } },
      { value: 'back_neck', label: { en: 'Back of head and neck', ta: 'தலையின் பின்புறம் மற்றும் பிடரி', hi: 'सिर के पीछे और गर्दन में' } },
    ],
  },
  {
    id: 'GM-HA-CHAR-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'headache',
    section: 'history_of_present_illness',
    category: 'character',
    questionText: {
      en: 'What does the headache feel like?',
      ta: 'தலைவலி உணர்வு எப்படி உள்ளது?',
      hi: 'सिरदर्द किस तरह का महसूस हो रहा है?',
    },
    answerType: 'single_choice',
    targetField: 'character_quality',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'throbbing', label: { en: 'Throbbing / Pulsating', ta: 'நரம்பு துடிப்பது போல்', hi: 'धुकधुक या टीस मारने वाला' } },
      { value: 'heavy_pressure', label: { en: 'Heavy pressure / Tight band', ta: 'தலை பாரமாக இறுக்கி பிடித்தது போல்', hi: 'भारी दबाव या कसाव जैसा' } },
      { value: 'sharp', label: { en: 'Sharp or stabbing', ta: 'கூரிய குத்தல் வலி', hi: 'तेज या चुभने वाला' } },
    ],
  },
  {
    id: 'GM-HA-SEV-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'headache',
    section: 'history_of_present_illness',
    category: 'severity',
    questionText: {
      en: 'On a scale of 1 to 10, how severe is your headache?',
      ta: '1 முதல் 10 வரையிலான அளவில் உங்கள் தலைவலி எவ்வளவு கடுமையானது?',
      hi: '1 से 10 के पैमाने पर आपका सिरदर्द कितना तेज है?',
    },
    answerType: 'numeric_scale',
    targetField: 'severity_score',
    priority: 80,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-HA-NECK-FEVER-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'headache',
    section: 'history_of_present_illness',
    category: 'red_flag_screening',
    questionText: {
      en: 'Do you have a stiff neck along with high fever?',
      ta: 'உங்களுக்கு அதிக காய்ச்சலுடன் கழுத்து விறைப்பு (குனிய முடியாத நிலை) உள்ளதா?',
      hi: 'क्या आपको तेज बुखार के साथ गर्दन में अकड़न भी है?',
    },
    answerType: 'yes_no',
    targetField: 'neck_stiffness_fever',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
  {
    id: 'GM-HA-NEURO-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'headache',
    section: 'history_of_present_illness',
    category: 'red_flag_screening',
    questionText: {
      en: 'Have you noticed any weakness in your arm/leg, numbness, or difficulty speaking?',
      ta: 'உங்களுக்கு கை/காலில் பலவீனம், மரத்துப்போதல் அல்லது பேச்சு தடுமாற்றம் உள்ளதா?',
      hi: 'क्या आपको हाथ/पैर में कमजोरी, सुन्नपन या बोलने में तकलीफ महसूस हो रही है?',
    },
    answerType: 'yes_no',
    targetField: 'focal_neurological_deficit',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
  {
    id: 'GM-HA-SENSITIVITY-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'headache',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Does bright light or loud sound make your headache worse?',
      ta: 'அதிக வெளிச்சம் அல்லது சத்தம் உங்கள் தலைவலியை அதிகமாக்குகிறதா?',
      hi: 'क्या तेज रोशनी या आवाज से सिरदर्द बढ़ जाता है?',
    },
    answerType: 'yes_no',
    targetField: 'photophobia_phonophobia',
    priority: 75,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
];
