import { ClinicalQuestion } from '../types';

export const JOINT_PAIN_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'GM-JOINT-LOC-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'joint_pain',
    section: 'history_of_present_illness',
    category: 'location',
    questionText: {
      en: 'Which joints are painful?',
      ta: 'எந்த மூட்டுகளில் வலி இருக்கிறது?',
      hi: 'किन जोड़ों में दर्द है?',
    },
    answerType: 'body_site',
    targetField: 'body_site',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'knees', label: { en: 'Knee joints', ta: 'முழங்கால்கள்', hi: 'घुटने' } },
      { value: 'small_joints_hands', label: { en: 'Small joints of hands and fingers', ta: 'கை விரல் மூட்டுகள்', hi: 'हाथों और उंगलियों के छोटे जोड़' } },
      { value: 'shoulders', label: { en: 'Shoulders', ta: 'தோள்பட்டைகள்', hi: 'कंधे' } },
      { value: 'multiple_joints', label: { en: 'Multiple joints across body', ta: 'உடல் முழுவதும் உள்ள பல மூட்டுகள்', hi: 'शरीर के कई जोड़' } },
    ],
  },
  {
    id: 'GM-JOINT-DUR-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'joint_pain',
    section: 'history_of_present_illness',
    category: 'duration',
    questionText: {
      en: 'How long have you had joint pain?',
      ta: 'எவ்வளவு நாட்களாக அல்லது மாதங்களாக மூட்டு வலி இருக்கிறது?',
      hi: 'आपको कितने समय से जोड़ों में दर्द है?',
    },
    answerType: 'duration',
    targetField: 'duration_text',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-JOINT-STIFFNESS-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'joint_pain',
    section: 'history_of_present_illness',
    category: 'timing',
    questionText: {
      en: 'Do you experience joint stiffness in the morning? How long does it last?',
      ta: 'காலையில் எழும்போது மூட்டுகள் விறைப்பாக இருக்குமா? அது எவ்வளவு நேரம் நீடிக்கும்?',
      hi: 'क्या सुबह उठने पर जोड़ों में जकड़न महसूस होती है? यह कितनी देर रहती है?',
    },
    answerType: 'single_choice',
    targetField: 'morning_stiffness_duration',
    priority: 85,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'none', label: { en: 'No morning stiffness', ta: 'காலை விறைப்பு இல்லை', hi: 'सुबह कोई जकड़न नहीं' } },
      { value: 'under_30mins', label: { en: 'Less than 30 minutes', ta: '30 நிமிடங்களுக்கும் குறைவு', hi: '30 मिनट से कम' } },
      { value: 'over_30mins', label: { en: 'More than 30-60 minutes', ta: '30 நிமிடங்களுக்கும் மேல்', hi: '30 मिनट से अधिक' } },
    ],
  },
  {
    id: 'GM-JOINT-SWELLING-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'joint_pain',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Is there visible swelling, redness, or warmth in the painful joints?',
      ta: 'வலி உள்ள மூட்டுகளில் வீக்கம், சிவப்பு நிறம் அல்லது சூடான உணர்வு உள்ளதா?',
      hi: 'क्या दर्द वाले जोड़ों में सूजन, लालिमा या गर्माहट है?',
    },
    answerType: 'yes_no',
    targetField: 'joint_swelling_redness',
    priority: 80,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
];
