import { ClinicalQuestion } from '../types';

export const URINARY_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'GM-URI-CHAR-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'urinary',
    section: 'history_of_present_illness',
    category: 'character',
    questionText: {
      en: 'What urinary problem are you experiencing?',
      ta: 'சிறுநீரில் உங்களுக்கு என்ன மாதிரியான தொந்தரவு உள்ளது?',
      hi: 'आपको पेशाब में क्या समस्या हो रही है?',
    },
    answerType: 'single_choice',
    targetField: 'urinary_symptom_type',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    choices: [
      { value: 'dysuria_burning', label: { en: 'Burning or pain during urination', ta: 'நீர் கழிக்கையில் எரிச்சல் / வலி', hi: 'पेशाब करते समय जलन या दर्द' } },
      { value: 'frequency_urgency', label: { en: 'Frequent urge to pass urine', ta: 'அடிக்கடி அவசரமாக நீர் கழிப்பது', hi: 'बार-बार पेशाब की हाजत होना' } },
      { value: 'nocturia', label: { en: 'Waking up multiple times at night to urinate', ta: 'இரவில் பலமுறை நீர் கழிக்க எழுவது', hi: 'रात में बार-बार पेशाब के लिए उठना' } },
      { value: 'weak_stream', label: { en: 'Difficulty starting or weak stream', ta: 'சிறுநீர் கழிக்க சிரமம் / மெல்லிய தாரை', hi: 'पेशाब शुरू करने में दिक्कत / धीमी धार' } },
    ],
  },
  {
    id: 'GM-URI-DUR-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'urinary',
    section: 'history_of_present_illness',
    category: 'duration',
    questionText: {
      en: 'How long have you had this urinary issue?',
      ta: 'எவ்வளவு நாட்களாக இந்த சிறுநீர் தொந்தரவு இருக்கிறது?',
      hi: 'आपको कितने दिनों से यह समस्या है?',
    },
    answerType: 'duration',
    targetField: 'duration_text',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-URI-HEMATURIA-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'urinary',
    section: 'history_of_present_illness',
    category: 'red_flag_screening',
    questionText: {
      en: 'Have you noticed red, pink, or cola-colored blood in your urine?',
      ta: 'சிறுநீரில் இரத்தம் அல்லது சிவப்பு நிறம் ஏதேனும் வந்ததா?',
      hi: 'क्या पेशाब में खून या लाल रंग दिखाई दिया है?',
    },
    answerType: 'yes_no',
    targetField: 'hematuria',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
  {
    id: 'GM-URI-FEVER-FLANK-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'urinary',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Do you have high fever, chills, or pain in your back/side (flank pain)?',
      ta: 'உங்களுக்கு அதிக காய்ச்சல், குளிர் நடுக்கம் அல்லது இடுப்பு/முதுகு பக்கவாட்டில் வலி உள்ளதா?',
      hi: 'क्या आपको तेज बुखार, ठंड या पीठ/कमर के तरफ दर्द है?',
    },
    answerType: 'yes_no',
    targetField: 'pyelonephritis_flank_pain',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
];
