import { ClinicalQuestion } from '../types';

export const VOMITING_QUESTIONS: ClinicalQuestion[] = [
  {
    id: 'GM-VOM-DUR-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'vomiting',
    section: 'history_of_present_illness',
    category: 'duration',
    questionText: {
      en: 'How long have you been vomiting?',
      ta: 'எவ்வளவு நேரமாக அல்லது நாட்களாக வாந்தி எடுக்கிறீர்கள்?',
      hi: 'आपको कितने समय से उल्टी हो रही है?',
    },
    answerType: 'duration',
    targetField: 'duration_text',
    priority: 90,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-VOM-FREQ-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'vomiting',
    section: 'history_of_present_illness',
    category: 'frequency',
    questionText: {
      en: 'How many times have you vomited today?',
      ta: 'இன்று எத்தனை முறை வாந்தி எடுத்தீர்கள்?',
      hi: 'आज कितनी बार उल्टी हुई है?',
    },
    answerType: 'numeric',
    targetField: 'vomiting_frequency',
    priority: 85,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
  },
  {
    id: 'GM-VOM-BLOOD-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'vomiting',
    section: 'history_of_present_illness',
    category: 'red_flag_screening',
    questionText: {
      en: 'Is there any blood or coffee-ground colored material in your vomit?',
      ta: 'வாந்தியில் இரத்தம் அல்லது காபி தூள் நிறத்தில் ஏதேனும் வந்ததா?',
      hi: 'क्या उल्टी में खून या कॉफी जैसे रंग का पदार्थ आया है?',
    },
    answerType: 'yes_no',
    targetField: 'hematemesis',
    priority: 95,
    required: true,
    voiceEnabled: true,
    touchEnabled: true,
    redFlagCandidate: true,
  },
  {
    id: 'GM-VOM-INTAKE-001',
    version: '1.0',
    mode: 'general_medicine',
    complaint: 'vomiting',
    section: 'history_of_present_illness',
    category: 'associated_symptoms',
    questionText: {
      en: 'Are you able to keep fluids down, or does water immediately trigger vomiting?',
      ta: 'தண்ணீர் குடித்தால் வயிற்றில் தங்குகிறதா அல்லது உடனே வாந்தி வருகிறதா?',
      hi: 'क्या पानी या तरल पदार्थ पेट में रुक रहा है या पीते ही उल्टी आ जाती है?',
    },
    answerType: 'yes_no',
    targetField: 'intake_tolerance',
    priority: 85,
    required: false,
    voiceEnabled: true,
    touchEnabled: true,
  },
];
