import * as React from 'react';
import { 
  User,
  ShieldCheck,
  Calendar,
  AlertTriangle,
  ClipboardList
} from 'lucide-react';

export interface PrintLayoutProps {
  reportId?: string;
  referenceNumber?: string;
  generatedAt?: string;
  patient?: {
    fullName: string;
    age?: number;
    gender?: string;
    hospitalNumber?: string;
    abhaReference?: string;
  };
  visit?: {
    generatedDate: string;
    departmentMode: 'standard' | 'ayush';
    intakeLanguage: string;
    reasonForVisit?: string;
  };
  clinicalHistory?: {
    chiefComplaint?: {
      primaryComplaint: string;
      additionalComplaints: string[];
      duration?: string;
    };
    hpi?: string;
    pastMedical?: string[];
    medications?: string[];
    allergies?: string[];
  };
  attentionFlags?: { label: string; message: string; severity: 'information' | 'review' | 'priority' }[];
  ayush?: { prakriti?: string; agni?: string };
}

export const PrintLayout: React.FC<PrintLayoutProps> = ({
  reportId = 'MK-RPT-000001',
  referenceNumber = 'REF-2026-0826',
  generatedAt = '2026-08-26 23:45:00',
  patient = {
    fullName: 'Arun Kumar',
    age: 45,
    gender: 'male',
    hospitalNumber: 'HSP-100245',
    abhaReference: 'ABHA-DEMO-001'
  },
  visit = {
    generatedDate: '2026-08-26',
    departmentMode: 'standard',
    intakeLanguage: 'English',
    reasonForVisit: 'Severe chest discomfort and shortness of breath.'
  },
  clinicalHistory = {
    chiefComplaint: {
      primaryComplaint: 'Chest Pain',
      additionalComplaints: ['Shortness of breath', 'Mild sweating'],
      duration: '3 hours'
    },
    hpi: 'Patient reports sudden onset of retrosternal pressure-like chest pain starting 3 hours ago while resting. Radiates slightly to the left shoulder. Severity is 7/10. Associated with mild dyspnea. Relieved partially by sitting up.',
    pastMedical: ['Hypertension (diagnosed 2021, on medication)', 'Type 2 Diabetes (diagnosed 2019)'],
    medications: ['Amlodipine 5mg OD', 'Metformin 500mg BD'],
    allergies: ['No Known Drug Allergies (NKDA)']
  },
  attentionFlags = [
    { label: 'Potential Priority Information — Requires Clinical Review', message: 'Patient reported chest pain. Requires immediate clinical assessment.', severity: 'priority' }
  ],
  ayush
}) => {
  return (
    <div className="print-container bg-white text-text-main p-8 max-w-4xl mx-auto border border-border-strong shadow-sm rounded-xl select-none">
      {/* Report Header */}
      <div className="flex justify-between items-start border-b-2 border-border-strong pb-4 mb-6">
        <div>
          <h2 className="text-xl font-extrabold text-secondary tracking-tight">CLINICAL INTAKE HISTORY SUMMARY</h2>
          <p className="text-xs text-text-secondary mt-1">Generated by MediKiosk on {generatedAt} — ID: {reportId}</p>
        </div>
        <div className="text-right flex flex-col items-end">
          <div className="h-16 w-16 bg-surface-muted border border-border-strong rounded flex items-center justify-center text-[10px] text-text-muted font-bold font-mono">
            QR CODE
          </div>
          <span className="text-[10px] font-mono text-text-muted mt-1.5">REF: {referenceNumber}</span>
        </div>
      </div>

      {/* Patient & Visit Metadata */}
      <div className="grid grid-cols-2 gap-6 bg-surface-muted p-4 rounded-lg border border-border-light mb-6">
        <div>
          <h4 className="text-xs font-bold text-secondary uppercase tracking-wider mb-2 flex items-center gap-1.5">
            <User className="h-4 w-4" /> Patient Demographics
          </h4>
          <table className="text-sm w-full">
            <tbody>
              <tr>
                <td className="text-text-secondary font-medium pb-1 pr-4">Full Name:</td>
                <td className="font-bold text-text-main pb-1">{patient.fullName}</td>
              </tr>
              <tr>
                <td className="text-text-secondary font-medium pb-1">Age / Gender:</td>
                <td className="font-semibold text-text-main pb-1">{patient.age} Y / {patient.gender}</td>
              </tr>
              <tr>
                <td className="text-text-secondary font-medium pb-1">Hospital ID:</td>
                <td className="font-mono text-text-main pb-1">{patient.hospitalNumber || 'N/A'}</td>
              </tr>
              <tr>
                <td className="text-text-secondary font-medium">ABHA Reference:</td>
                <td className="font-mono text-text-main">{patient.abhaReference || 'N/A'}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div>
          <h4 className="text-xs font-bold text-secondary uppercase tracking-wider mb-2 flex items-center gap-1.5">
            <Calendar className="h-4 w-4" /> Visit Details
          </h4>
          <table className="text-sm w-full">
            <tbody>
              <tr>
                <td className="text-text-secondary font-medium pb-1 pr-4">Intake Date:</td>
                <td className="font-semibold text-text-main pb-1">{visit.generatedDate}</td>
              </tr>
              <tr>
                <td className="text-text-secondary font-medium pb-1">Intake Lang:</td>
                <td className="font-semibold text-text-main pb-1">{visit.intakeLanguage}</td>
              </tr>
              <tr>
                <td className="text-text-secondary font-medium pb-1">Dept Mode:</td>
                <td className="font-bold text-text-main pb-1">{visit.departmentMode === 'ayush' ? 'AYUSH' : 'Standard'}</td>
              </tr>
              <tr>
                <td className="text-text-secondary font-medium">Report Version:</td>
                <td className="font-mono text-text-main">v1.0 (Draft)</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Safety Attention Flags */}
      {attentionFlags && attentionFlags.length > 0 && (
        <div className="border-2 border-priority bg-priority-light p-4 rounded-xl mb-6 print-avoid-break">
          <h4 className="text-sm font-extrabold text-priority flex items-center gap-2 mb-1.5 uppercase tracking-wide">
            <AlertTriangle className="h-5 w-5 fill-priority/10" /> {attentionFlags[0].label}
          </h4>
          <p className="text-sm text-text-main leading-relaxed font-semibold">
            {attentionFlags[0].message}
          </p>
        </div>
      )}

      {/* Clinical History Content */}
      <div className="space-y-6">
        {/* Chief Complaint */}
        {clinicalHistory.chiefComplaint && (
          <div className="print-avoid-break">
            <h3 className="text-sm font-bold text-secondary uppercase tracking-wider border-b border-border-strong pb-1 mb-2">
              1. Chief Complaint
            </h3>
            <p className="text-sm leading-relaxed text-text-main">
              Patient presents with <span className="font-bold">{clinicalHistory.chiefComplaint.primaryComplaint}</span> for a duration of <span className="font-semibold">{clinicalHistory.chiefComplaint.duration || 'N/A'}</span>.
              {clinicalHistory.chiefComplaint.additionalComplaints.length > 0 && (
                <span> Associated with: {clinicalHistory.chiefComplaint.additionalComplaints.join(', ')}.</span>
              )}
            </p>
          </div>
        )}

        {/* History of Present Illness */}
        {clinicalHistory.hpi && (
          <div className="print-avoid-break">
            <h3 className="text-sm font-bold text-secondary uppercase tracking-wider border-b border-border-strong pb-1 mb-2">
              2. History of Present Illness (HPI)
            </h3>
            <p className="text-sm leading-relaxed text-text-main">
              {clinicalHistory.hpi}
            </p>
          </div>
        )}

        {/* Medical History & Current Medications */}
        <div className="grid grid-cols-2 gap-6 print-avoid-break">
          <div>
            <h3 className="text-sm font-bold text-secondary uppercase tracking-wider border-b border-border-strong pb-1 mb-2">
              3. Past Medical Conditions
            </h3>
            {clinicalHistory.pastMedical && clinicalHistory.pastMedical.length > 0 ? (
              <ul className="list-disc pl-4 text-sm text-text-main space-y-1">
                {clinicalHistory.pastMedical.map((med, idx) => (
                  <li key={idx}>{med}</li>
                ))}
              </ul>
            ) : (
              <p className="text-sm text-text-muted">None reported.</p>
            )}
          </div>

          <div>
            <h3 className="text-sm font-bold text-secondary uppercase tracking-wider border-b border-border-strong pb-1 mb-2">
              4. Current Medications
            </h3>
            {clinicalHistory.medications && clinicalHistory.medications.length > 0 ? (
              <ul className="list-disc pl-4 text-sm text-text-main space-y-1">
                {clinicalHistory.medications.map((med, idx) => (
                  <li key={idx}>{med}</li>
                ))}
              </ul>
            ) : (
              <p className="text-sm text-text-muted">None reported.</p>
            )}
          </div>
        </div>

        {/* Allergies */}
        <div className="print-avoid-break">
          <h3 className="text-sm font-bold text-secondary uppercase tracking-wider border-b border-border-strong pb-1 mb-2">
            5. Allergies
          </h3>
          {clinicalHistory.allergies && clinicalHistory.allergies.length > 0 ? (
            <ul className="list-disc pl-4 text-sm text-text-main space-y-1">
              {clinicalHistory.allergies.map((allergy, idx) => (
                <li key={idx} className="font-semibold text-error">{allergy}</li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-text-muted">No known drug/food allergies reported.</p>
          )}
        </div>

        {/* AYUSH Assessment section */}
        {visit.departmentMode === 'ayush' && (
          <div className="print-avoid-break border border-ayush-border bg-ayush-light p-4 rounded-xl">
            <h3 className="text-sm font-bold text-ayush uppercase tracking-wider border-b border-ayush-border pb-1 mb-2">
              6. AYUSH Ayurvedic Intake Parameters
            </h3>
            <table className="text-sm w-full">
              <tbody>
                <tr>
                  <td className="text-text-secondary font-medium pb-1 pr-4 w-1/3">Prakriti (Constitution):</td>
                  <td className="font-bold text-text-main pb-1">{ayush?.prakriti || 'Vata-Pitta'}</td>
                </tr>
                <tr>
                  <td className="text-text-secondary font-medium">Agni (Metabolic fire):</td>
                  <td className="font-bold text-text-main">{ayush?.agni || 'Manda Agni (Slow)'}</td>
                </tr>
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Manual Physician Corrections Area */}
      <div className="mt-8 border border-border-strong rounded-xl p-5 bg-surface-muted print-avoid-break">
        <h4 className="text-xs font-bold text-secondary uppercase tracking-wider mb-2 flex items-center gap-1.5">
          <ClipboardList className="h-4 w-4" /> Clinician Notes & Corrections
        </h4>
        <div className="h-24 border border-dashed border-border-strong bg-white rounded-lg p-3 text-xs text-text-muted">
          Use this area to write clinical overrides, adjustments, or additional symptom details...
        </div>
      </div>

      {/* Verification & Sign-off area */}
      <div className="mt-8 pt-6 border-t border-border-strong flex justify-between items-end print-avoid-break">
        <div className="max-w-md">
          <p className="text-[10px] text-text-secondary leading-normal flex items-start gap-1">
            <ShieldCheck className="h-3.5 w-3.5 text-success shrink-0" />
            <span>
              Disclaimer: This is a patient-reported clinical intake summary draft generated by MediKiosk. It is NOT a clinical diagnosis or treatment prescription. All details must be verified by the physician prior to clinical action.
            </span>
          </p>
        </div>
        <div className="w-56 text-right">
          <div className="h-10 border-b border-border-strong mb-1"></div>
          <p className="text-xs font-bold text-text-main">Physician Signature</p>
          <p className="text-[10px] text-text-muted">Date: ____/____/2026 Time: ____:____</p>
        </div>
      </div>
    </div>
  );
};
