import { z } from 'zod';

export const AuditActionSchema = z.enum([
  'session_started',
  'patient_identified',
  'consent_accepted',
  'consent_declined',
  'question_answered',
  'answer_edited',
  'document_uploaded',
  'document_processed',
  'history_generation_started',
  'history_generation_completed',
  'history_generation_failed',
  'report_generated',
  'print_started',
  'print_completed',
  'session_expired',
  'session_cleaned',
  'session_cancelled',
  'document_ocr_started',
  'document_ocr_completed',
  'document_ocr_failed',
  'document_ocr_retry',
  'clinical_extraction_started',
  'clinical_extraction_completed',
  'clinical_extraction_failed',
  'clinical_extraction_retry',
  'clinical_extraction_requires_review',
  'timeline_generation_started',
  'timeline_generation_completed',
  'timeline_generation_failed',
  'record_conflict_detected',
  'attention_evaluation_started',
  'attention_flag_created',
  'attention_flag_updated',
  'attention_evaluation_completed',
  'attention_evaluation_failed',
]);

export const AuditLogSchema = z.object({
  id: z.string(),
  sessionId: z.string().optional(),
  action: AuditActionSchema,
  entityType: z.string().optional(),
  entityId: z.string().optional(),
  timestamp: z.string(),
  metadata: z.record(z.string(), z.unknown()).optional(),
});
