import { Question } from '../../types';

export const PHASE6_DEMO_QUESTIONS: Question[] = [
  // SECTION A — REASON FOR VISIT
  {
    id: 'reason_for_visit',
    section: 'chief_complaint',
    displayOrder: 1,
    question: {
      en: 'Please describe the main reason for your visit today.',
      hi: 'कृपया आज आने का मुख्य कारण बताएं।',
      ta: 'இன்று நீங்கள் வந்ததற்கான முக்கிய காரணத்தை விவரிக்கவும்.',
    },
    inputType: 'text',
    informationFields: ['chief_complaint'],
    required: true,
    allowVoice: true,
    allowTouch: true,
    helpText: {
      en: 'You can use the on-screen keyboard or speak your answer.',
    },
  },
  {
    id: 'symptom_duration',
    section: 'chief_complaint',
    displayOrder: 2,
    question: {
      en: 'Approximately how long have you had this problem?',
      hi: 'लगभग कितने समय से आपको यह समस्या है?',
      ta: 'சுமார் எவ்வளவு காலமாக உங்களுக்கு இந்தப் பிரச்சனை இருக்கிறது?',
    },
    inputType: 'single_choice',
    informationFields: ['duration'],
    required: true,
    allowVoice: true,
    allowTouch: true,
    options: [
      { id: 'lt1', value: 'lt1', label: 'Less than 1 day' },
      { id: '1to3', value: '1to3', label: '1–3 days' },
      { id: '4to7', value: '4to7', label: '4–7 days' },
      { id: 'gt7', value: 'gt7', label: 'More than 1 week' },
    ],
  },
  // SECTION B — SIMPLE FOLLOW-UP
  {
    id: 'symptom_progression',
    section: 'hpi',
    displayOrder: 3,
    question: {
      en: 'Is the problem getting better, worse, or staying about the same?',
      hi: 'क्या समस्या बेहतर हो रही है, बदतर हो रही है, या लगभग वैसी ही है?',
      ta: 'பிரச்சனை குணமாகிறதா, மோசமாகிறதா அல்லது அப்படியே இருக்கிறதா?',
    },
    inputType: 'single_choice',
    informationFields: ['progression'],
    required: true,
    allowVoice: true,
    allowTouch: true,
    options: [
      { id: 'better', value: 'better', label: 'Getting better' },
      { id: 'worse', value: 'worse', label: 'Getting worse' },
      { id: 'same', value: 'same', label: 'About the same' },
      { id: 'not_sure', value: 'not_sure', label: 'Not sure' },
    ],
  },
  // SECTION C — BASIC SAFETY DEMONSTRATION (Conditional Routing)
  {
    id: 'safety_check',
    section: 'review_of_systems',
    displayOrder: 4,
    question: {
      en: 'Are you currently experiencing any severe pain?',
      hi: 'क्या आपको वर्तमान में कोई गंभीर दर्द हो रहा है?',
      ta: 'தற்போது உங்களுக்கு ஏதேனும் கடுமையான வலி உள்ளதா?',
    },
    inputType: 'yes_no',
    informationFields: ['pain_presence'],
    required: true,
    allowVoice: true,
    allowTouch: true,
    followUpRules: [
      {
        condition: {
          fieldId: 'safety_check',
          operator: 'equals',
          value: 'yes',
        },
        nextQuestionId: 'pain_location',
      },
      {
        condition: {
          fieldId: 'safety_check',
          operator: 'equals',
          value: 'no',
        },
        nextQuestionId: 'pain_scale', // skip pain_location, go to scale just to show routing
      }
    ],
  },
  {
    id: 'pain_location',
    section: 'review_of_systems',
    displayOrder: 3,
    question: {
      en: 'Where exactly is the pain or discomfort located?',
      hi: 'दर्द या बेचैनी ठीक किस जगह पर है?',
      ta: 'வலி அல்லது அசௌகரியம் சரியாக எந்த இடத்தில் உள்ளது?',
    },
    inputType: 'text',
    informationFields: ['location'],
    required: true,
    allowVoice: true,
    allowTouch: true,
  },
  {
    id: 'symptom_character',
    section: 'hpi',
    displayOrder: 4,
    question: {
      en: 'How would you describe the feeling of the pain or discomfort (such as burning, sharp, dull, throbbing, or pressure)?',
      hi: 'आप दर्द या बेचैनी को कैसे समझाएंगे (जैसे जलन, तेज, धीमा, धड़कने वाला या दबाव)?',
      ta: 'வலி அல்லது அசௌகரியத்தை எவ்வாறு விவரிப்பீர்கள் (எரிச்சல், கூர்மையான, மந்தமான, துடிக்கும் அல்லது அழுத்தம்)?',
    },
    inputType: 'text',
    informationFields: ['character_quality'],
    required: false,
    allowVoice: true,
    allowTouch: true,
  },
  {
    id: 'pain_scale',
    section: 'review_of_systems',
    displayOrder: 5,
    question: {
      en: 'On a scale from 1 to 10, how severe is the pain, where 1 is very mild and 10 is the worst pain?',
      hi: '1 से 10 के पैमाने पर, दर्द कितना गंभीर है, जहाँ 1 बहुत हल्का है और 10 सबसे गंभीर दर्द है?',
      ta: '1 முதல் 10 வரையிலான அளவில், வலி எவ்வளவு கடுமையானது, இதில் 1 மிகவும் லேசானது மற்றும் 10 மிகவும் கடுமையானது?',
    },
    inputType: 'number',
    informationFields: ['severity'],
    required: true,
    allowVoice: true,
    allowTouch: true,
  },
  {
    id: 'symptom_progression',
    section: 'hpi',
    displayOrder: 6,
    question: {
      en: 'Is the problem getting better, worse, or staying about the same?',
      hi: 'क्या समस्या बेहतर हो रही है, बदतर हो रही है, या लगभग वैसी ही है?',
      ta: 'பிரச்சனை குணமாகிறதா, மோசமாகிறதா அல்லது அப்படியே இருக்கிறதா?',
    },
    inputType: 'single_choice',
    informationFields: ['progression'],
    required: true,
    allowVoice: true,
    allowTouch: true,
    options: [
      { id: 'better', value: 'better', label: 'Getting better' },
      { id: 'worse', value: 'worse', label: 'Getting worse' },
      { id: 'same', value: 'same', label: 'About the same' },
      { id: 'not_sure', value: 'not_sure', label: 'Not sure' },
    ],
  },
  {
    id: 'aggravating_relieving',
    section: 'hpi',
    displayOrder: 7,
    question: {
      en: 'Does anything make the symptoms better or worse (such as eating, resting, movement, or medicines)?',
      hi: 'क्या किसी चीज से लक्षण बेहतर या बदतर होते हैं (जैसे खाना, आराम करना, चलना या दवाएं)?',
      ta: 'ஏதேனும் காரணி அறிகுறிகளை சிறப்பாகவோ அல்லது மோசமாகவோ ஆக்குகிறதா (உணவு, ஓய்வு, இயக்கம், மருந்துகள்)?',
    },
    inputType: 'text',
    informationFields: ['aggravating_relieving'],
    required: false,
    allowVoice: true,
    allowTouch: true,
  },
  {
    id: 'associated_symptoms',
    section: 'hpi',
    displayOrder: 8,
    question: {
      en: 'Are you experiencing any other symptoms along with this (such as fever, nausea, dizziness, or shortness of breath)?',
      hi: 'क्या आपको इसके साथ कोई अन्य लक्षण (जैसे बुखार, मतली, चक्कर आना या सांस लेने में तकलीफ) का अनुभव हो रहा है?',
      ta: 'இதனுடன் ஏதேனும் மற்ற அறிகுறிகள் (காய்ச்சல், குமட்டல், தலைச்சுற்றல் போன்றவை) உணர்கிறீர்களா?',
    },
    inputType: 'text',
    informationFields: ['associated_symptoms'],
    required: false,
    allowVoice: true,
    allowTouch: true,
  },
  {
    id: 'previous_treatments',
    section: 'hpi',
    displayOrder: 9,
    question: {
      en: 'Have you taken any medicines, home remedies, or treatments for this problem so far?',
      hi: 'क्या आपने इस समस्या के लिए अब तक कोई दवाएं, घरेलू उपचार या इलाज लिया है?',
      ta: 'இந்த பிரச்சனைக்கு இதுவரை ஏதேனும் மருந்துகள், வீட்டு வைத்தியம் அல்லது சிகிச்சைகள் எடுத்துள்ளீர்களா?',
    },
    inputType: 'text',
    informationFields: ['previous_treatments'],
    required: false,
    allowVoice: true,
    allowTouch: true,
  },
  {
    id: 'past_medical_history',
    section: 'past_medical_history',
    displayOrder: 10,
    question: {
      en: 'Do you have any existing medical conditions (such as Diabetes, High Blood Pressure, Asthma, or Heart disease)?',
      hi: 'क्या आपको कोई पहले से मौजूद बीमारी (जैसे मधुमेह, उच्च रक्तचाप, अस्थमा या हृदय रोग) है?',
      ta: 'உங்களுக்கு ஏற்கனவே ஏதேனும் மருத்துவ நிலைமைகள் (நீரிழிவு, உயர் இரத்த அழுத்தம், ஆஸ்துமா போன்றவை) உள்ளதா?',
    },
    inputType: 'text',
    informationFields: ['past_conditions'],
    required: false,
    allowVoice: true,
    allowTouch: true,
  },
  {
    id: 'current_medications',
    section: 'medications',
    displayOrder: 11,
    question: {
      en: 'Are you currently taking any regular medications or supplements?',
      hi: 'क्या आप वर्तमान में कोई नियमित दवाएं या पूरक ले रहे हैं?',
      ta: 'நீங்கள் தற்போது ஏதேனும் வழக்கமான மருந்துகளை உட்கொள்கிறீர்களா?',
    },
    inputType: 'text',
    informationFields: ['medications'],
    required: false,
    allowVoice: true,
    allowTouch: true,
  },
  // SECTION D — DYNAMIC CLINICAL DIFFERENTIAL QUESTIONS
  {
    id: 'stomach_pain_triggers',
    section: 'hpi',
    displayOrder: 10,
    question: {
      en: 'Does the burning stomach pain get better or worse after eating meals or taking antacids?',
      hi: 'क्या भोजन करने या एंटासिड लेने के बाद पेट की जलन बेहतर या बदतर हो जाती है?',
      ta: 'உணவு சாப்பிட்ட பிறகு அல்லது அமில எதிர்ப்பு மருந்து எடுத்த பிறகு வயிற்று எரிச்சல் குறைகிறதா அல்லது அதிகமாகிறதா?',
    },
    inputType: 'single_choice',
    informationFields: ['aggravating_factors'],
    required: false,
    allowVoice: true,
    allowTouch: true,
    options: [
      { id: 'worse_after_eating', value: 'worse_after_eating', label: 'Worse after eating meals' },
      { id: 'better_after_eating', value: 'better_after_eating', label: 'Better after eating' },
      { id: 'better_with_antacids', value: 'better_with_antacids', label: 'Relieved by antacids' },
      { id: 'no_change', value: 'no_change', label: 'No difference with food' },
    ],
  },
  {
    id: 'gi_red_flags',
    section: 'review_of_systems',
    displayOrder: 11,
    question: {
      en: 'Have you noticed any acid regurgitation, nausea, vomiting, or dark black stools?',
      hi: 'क्या आपने खट्टी डकारें, जी मिचलाना, उल्टी, या काले रंग का मल देखा है?',
      ta: 'அமில எதிரொளிப்பு, குமட்டல், வாந்தி அல்லது கருப்பு நிற மலம் ஏதேனும் கவனித்துள்ளீர்களா?',
    },
    inputType: 'single_choice',
    informationFields: ['associated_gi_symptoms'],
    required: false,
    allowVoice: true,
    allowTouch: true,
    options: [
      { id: 'acid_reflux', value: 'acid_reflux', label: 'Acid reflux / Sour burps' },
      { id: 'nausea_vomiting', value: 'nausea_vomiting', label: 'Nausea or vomiting' },
      { id: 'dark_stools', value: 'dark_stools', label: 'Dark or black stools' },
      { id: 'none', value: 'none', label: 'None of these' },
    ],
  },
  {
    id: 'cardiac_radiation_check',
    section: 'review_of_systems',
    displayOrder: 12,
    question: {
      en: 'Does the chest pain or tightness spread to your left arm, neck, shoulder, or jaw?',
      hi: 'क्या सीने में दर्द या दबाव आपके बाएं हाथ, गर्दन या जबड़े में फैलता है?',
      ta: 'மார்பு வலி அல்லது அழுத்தம் உங்கள் இடது கை, கழுத்து அல்லது தாடைக்கு பரவுகிறதா?',
    },
    inputType: 'single_choice',
    informationFields: ['pain_radiation'],
    required: false,
    allowVoice: true,
    allowTouch: true,
    options: [
      { id: 'left_arm', value: 'left_arm', label: 'Spreads to left arm / shoulder' },
      { id: 'neck_jaw', value: 'neck_jaw', label: 'Spreads to neck or jaw' },
      { id: 'back', value: 'back', label: 'Spreads to back' },
      { id: 'localized', value: 'localized', label: 'Stays in chest only' },
    ],
  },
];

export const PHASE13_AYUSH_QUESTIONS: Question[] = [
  // SECTION A — REASON FOR VISIT (Same as allopathic but could be tailored, we use standard chief complaint)
  {
    id: 'reason_for_visit',
    section: 'chief_complaint',
    displayOrder: 1,
    question: {
      en: 'Please describe the main reason for your visit today.',
      hi: 'कृपया आज आने का मुख्य कारण बताएं।',
      ta: 'இன்று நீங்கள் வந்ததற்கான முக்கிய காரணத்தை விவரிக்கவும்.',
    },
    inputType: 'text',
    informationFields: ['chief_complaint'],
    required: true,
    allowVoice: true,
    allowTouch: true,
    helpText: {
      en: 'You can use the on-screen keyboard or speak your answer.',
    },
  },
  {
    id: 'symptom_duration',
    section: 'chief_complaint',
    displayOrder: 2,
    question: {
      en: 'Approximately how long have you had this problem?',
      hi: 'लगभग कितने समय से आपको यह समस्या है?',
      ta: 'சுமார் எவ்வளவு காலமாக உங்களுக்கு இந்தப் பிரச்சனை இருக்கிறது?',
    },
    inputType: 'single_choice',
    informationFields: ['duration'],
    required: true,
    allowVoice: true,
    allowTouch: true,
    options: [
      { id: 'lt1', value: 'lt1', label: 'Less than 1 day' },
      { id: '1to3', value: '1to3', label: '1–3 days' },
      { id: '4to7', value: '4to7', label: '4–7 days' },
      { id: 'gt7', value: 'gt7', label: 'More than 1 week' },
    ],
  },
  // AYUSH SPECIFIC - DASHAVIDHA PARIKSHA
  {
    id: 'ayush_prakriti',
    section: 'ayush',
    displayOrder: 3,
    question: {
      en: 'How would you describe your general body constitution or body type? (e.g., thin, medium, heavy build, or specific dosha if known)',
      hi: 'आप अपने सामान्य शारीरिक गठन का वर्णन कैसे करेंगे?',
      ta: 'உங்கள் உடல் அமைப்பை எவ்வாறு விவரிப்பீர்கள்?',
    },
    inputType: 'text',
    informationFields: ['prakriti'],
    required: false,
    allowVoice: true,
    allowTouch: true,
  },
  {
    id: 'ayush_digestion',
    section: 'ayush',
    displayOrder: 4,
    question: {
      en: 'How is your digestion (Agni)?',
      hi: 'आपका पाचन कैसा है?',
      ta: 'உங்கள் செரிமானம் எப்படி உள்ளது?',
    },
    inputType: 'single_choice',
    informationFields: ['agni'],
    required: true,
    allowVoice: true,
    allowTouch: true,
    options: [
      { id: 'good', value: 'good', label: 'Good and regular' },
      { id: 'irregular', value: 'irregular', label: 'Irregular or varying' },
      { id: 'weak', value: 'weak', label: 'Weak or slow' },
      { id: 'intense', value: 'intense', label: 'Very intense / often hungry' },
    ],
  },
  {
    id: 'ayush_bowel',
    section: 'ayush',
    displayOrder: 5,
    question: {
      en: 'How are your bowel movements (Koshtha)?',
      hi: 'आपका मलत्याग कैसा है?',
      ta: 'உங்கள் குடல் இயக்கம் எப்படி உள்ளது?',
    },
    inputType: 'single_choice',
    informationFields: ['koshtha'],
    required: true,
    allowVoice: true,
    allowTouch: true,
    options: [
      { id: 'regular', value: 'regular', label: 'Regular and soft' },
      { id: 'hard', value: 'hard', label: 'Hard or constipated' },
      { id: 'loose', value: 'loose', label: 'Loose or frequent' },
      { id: 'variable', value: 'variable', label: 'Variable' },
    ],
  },
  {
    id: 'ayush_sleep',
    section: 'ayush',
    displayOrder: 6,
    question: {
      en: 'How would you describe your sleep quality?',
      hi: 'आपकी नींद कैसी है?',
      ta: 'உங்கள் தூக்கம் எப்படி உள்ளது?',
    },
    inputType: 'single_choice',
    informationFields: ['sleep_quality'],
    required: true,
    allowVoice: true,
    allowTouch: true,
    options: [
      { id: 'deep', value: 'deep', label: 'Deep and uninterrupted' },
      { id: 'disturbed', value: 'disturbed', label: 'Disturbed / broken sleep' },
      { id: 'light', value: 'light', label: 'Light sleep / hard to fall asleep' },
      { id: 'excessive', value: 'excessive', label: 'Excessive or feeling sleepy all day' },
    ],
  },
  {
    id: 'ayush_diet',
    section: 'ayush',
    displayOrder: 7,
    question: {
      en: 'What type of food do you usually consume? (Ahara)',
      hi: 'आप आमतौर पर किस प्रकार का भोजन करते हैं?',
      ta: 'நீங்கள் வழக்கமாக என்ன வகையான உணவை உட்கொள்கிறீர்கள்?',
    },
    inputType: 'text',
    informationFields: ['ahara'],
    required: false,
    allowVoice: true,
    allowTouch: true,
    helpText: {
      en: 'Describe your daily diet, preferred tastes, and whether you eat mostly hot/cold foods.',
    },
  },
  {
    id: 'ayush_exercise',
    section: 'ayush',
    displayOrder: 8,
    question: {
      en: 'How much physical activity do you get daily? (Vyayama Shakti)',
      hi: 'आप प्रतिदिन कितनी शारीरिक गतिविधि करते हैं?',
      ta: 'தினசரி நீங்கள் எவ்வளவு உடற்பயிற்சி செய்கிறீர்கள்?',
    },
    inputType: 'single_choice',
    informationFields: ['vyayama_shakti'],
    required: true,
    allowVoice: true,
    allowTouch: true,
    options: [
      { id: 'none', value: 'none', label: 'None / Sedentary' },
      { id: 'light', value: 'light', label: 'Light (walking, yoga)' },
      { id: 'moderate', value: 'moderate', label: 'Moderate' },
      { id: 'heavy', value: 'heavy', label: 'Heavy / Strenuous' },
    ],
  },
  {
    id: 'ayush_mind',
    section: 'ayush',
    displayOrder: 9,
    question: {
      en: 'How would you describe your mental state currently? (Satva)',
      hi: 'आप अपनी वर्तमान मानसिक स्थिति का वर्णन कैसे करेंगे?',
      ta: 'தற்போது உங்கள் மன நிலையை எவ்வாறு விவரிப்பீர்கள்?',
    },
    inputType: 'single_choice',
    required: true,
    allowVoice: true,
    allowTouch: true,
    options: [
      { id: 'calm', value: 'calm', label: 'Calm and clear' },
      { id: 'anxious', value: 'anxious', label: 'Anxious or restless' },
      { id: 'angry', value: 'angry', label: 'Irritable or angry' },
      { id: 'dull', value: 'dull', label: 'Dull or unmotivated' },
    ],
  },
];
